/**
 * lib/debug/debug-bundle-export.ts
 *
 * Sprint 58: Exports a DebugSummary as DEBUG_BUNDLE.md.
 *
 * Pure function — no secrets, no side effects.
 */

import type { DebugSummary, DebugFinding } from "./debug-types";

const SEVERITY_ICON: Record<string, string> = {
  critical: "🔴",
  error:    "🟠",
  warning:  "🟡",
  info:     "🔵",
};

function formatFinding(f: DebugFinding): string {
  const lines: string[] = [
    `### ${SEVERITY_ICON[f.severity] ?? "⚪"} ${f.title}`,
    `**Category:** ${f.category}  **Severity:** ${f.severity}`,
    "",
    f.message,
  ];
  if (f.evidence && f.evidence.length > 0) {
    lines.push("", "**Evidence:**", "```", ...f.evidence, "```");
  }
  if (f.suggestedFix) {
    lines.push("", `**Suggested fix:** ${f.suggestedFix}`);
  }
  if (f.fixHref) {
    lines.push("", `**Fix page:** [Open →](${f.fixHref})`);
  }
  return lines.join("\n");
}

export function exportDebugBundle(
  summary: DebugSummary,
  projectName: string,
): string {
  const STATUS_ICON: Record<string, string> = {
    healthy: "✅",
    warning: "⚠️",
    failed:  "❌",
    unknown: "❓",
  };

  const lines: string[] = [
    "# DEBUG_BUNDLE.md",
    "",
    `**Project:** ${projectName}`,
    `**Generated:** ${new Date(summary.generatedAt).toLocaleString()}`,
    `**Source:** ${summary.source}`,
    `**Status:** ${STATUS_ICON[summary.status] ?? ""} ${summary.status}`,
    "",
    "---",
    "",
  ];

  // Likely cause
  if (summary.likelyCause) {
    lines.push("## Likely Cause", "", summary.likelyCause, "");
  }

  // Findings
  if (summary.findings.length > 0) {
    lines.push("## Findings", "");

    // Group by category
    const byCategory = new Map<string, DebugFinding[]>();
    for (const f of summary.findings) {
      const arr = byCategory.get(f.category) ?? [];
      arr.push(f);
      byCategory.set(f.category, arr);
    }

    for (const [cat, catFindings] of byCategory) {
      lines.push(`### ${cat.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}`, "");
      for (const f of catFindings) {
        lines.push(formatFinding(f), "");
      }
    }
  } else {
    lines.push("## Findings", "", "_No known error patterns detected._", "");
  }

  // Sanitized excerpt
  if (summary.sanitizedExcerpt) {
    lines.push(
      "## Sanitized Log Excerpt",
      "",
      "> All credentials and secrets have been redacted.",
      "",
      "```",
      summary.sanitizedExcerpt,
      "```",
      "",
    );
  }

  // Next steps
  if (summary.nextSteps.length > 0) {
    lines.push("## Next Steps", "");
    for (const step of summary.nextSteps) {
      lines.push(`- [ ] ${step}`);
    }
    lines.push("");
  }

  // Support checklist
  lines.push(
    "## Support Checklist",
    "",
    "Before opening a support request, confirm:",
    "",
    "- [ ] Environment variables are set (check the Env page)",
    "- [ ] Database is reachable and migrations have run",
    "- [ ] Build passes locally (`pnpm run build`)",
    "- [ ] PM2 process is running (`pm2 list`)",
    "- [ ] No secrets are included in this bundle",
    "",
    "---",
    "",
    `_Generated by Prisom Project Panel — Sprint 58_`,
  );

  return lines.join("\n");
}
