/**
 * lib/deploy/dry-run-export.ts
 *
 * Sprint 53: Export a deployment dry-run plan as a Markdown report.
 *
 * Safety rules:
 *  - no secrets included
 *  - no live deploy triggered
 *  - report is read-only documentation
 */

import type { DeploymentDryRunPlan, DeploymentDryRunReport, DeploymentDryRunCheck } from "./dry-run-types";

const CATEGORY_LABEL: Record<string, string> = {
  source:          "Source",
  package_manager: "Package Manager",
  install:         "Install",
  build:           "Build",
  services:        "Services",
  env:             "Environment",
  database:        "Database",
  routing:         "Routing",
  domain:          "Domain",
  smoke:           "Smoke Checks",
  manual:          "Manual Steps",
};

function statusEmoji(status: DeploymentDryRunCheck["status"]): string {
  if (status === "pass")    return "✅";
  if (status === "warning") return "⚠️";
  if (status === "fail")    return "❌";
  return "📋";
}

export function buildDeploymentDryRunReport(plan: DeploymentDryRunPlan): DeploymentDryRunReport {
  const checks = plan.checks;
  return {
    projectId:   plan.projectId,
    generatedAt: plan.generatedAt,
    status:      plan.status,
    summary: {
      total:    checks.length,
      passed:   checks.filter((c) => c.status === "pass").length,
      warnings: checks.filter((c) => c.status === "warning").length,
      failed:   checks.filter((c) => c.status === "fail").length,
      manual:   checks.filter((c) => c.status === "manual").length,
    },
    checks:    plan.checks,
    blockers:  plan.blockers,
    warnings:  plan.warnings,
    nextSteps: plan.nextSteps,
  };
}

export function exportDeploymentDryRunReport(
  plan:        DeploymentDryRunPlan,
  projectName: string,
): string {
  const report  = buildDeploymentDryRunReport(plan);
  const lines:  string[] = [];
  const genDate = new Date(plan.generatedAt).toLocaleString("en-GB", {
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit",
  });

  lines.push(`# DEPLOYMENT_DRY_RUN_REPORT`);
  lines.push(``);
  lines.push(`**Project:** ${projectName}`);
  lines.push(`**Generated:** ${genDate}`);
  lines.push(`**Status:** ${plan.status.toUpperCase()}`);
  lines.push(``);
  lines.push(`---`);
  lines.push(``);

  // Summary
  lines.push(`## Summary`);
  lines.push(``);
  lines.push(`| Metric   | Count |`);
  lines.push(`|----------|-------|`);
  lines.push(`| Total    | ${report.summary.total} |`);
  lines.push(`| Passed   | ${report.summary.passed} |`);
  lines.push(`| Warnings | ${report.summary.warnings} |`);
  lines.push(`| Failed   | ${report.summary.failed} |`);
  lines.push(`| Manual   | ${report.summary.manual} |`);
  lines.push(``);

  // Blockers
  if (report.blockers.length > 0) {
    lines.push(`## ❌ Blockers — Must Resolve Before Deploy`);
    lines.push(``);
    for (const b of report.blockers) {
      lines.push(`- ${b}`);
    }
    lines.push(``);
  }

  // Warnings
  if (report.warnings.length > 0) {
    lines.push(`## ⚠️ Warnings`);
    lines.push(``);
    for (const w of report.warnings) {
      lines.push(`- ${w}`);
    }
    lines.push(``);
  }

  // Grouped checks
  const categories = Array.from(new Set(report.checks.map((c) => c.category)));
  lines.push(`## Checks by Category`);
  lines.push(``);

  for (const cat of categories) {
    const catChecks = report.checks.filter((c) => c.category === cat);
    if (catChecks.length === 0) continue;

    lines.push(`### ${CATEGORY_LABEL[cat] ?? cat}`);
    lines.push(``);

    for (const c of catChecks) {
      lines.push(`${statusEmoji(c.status)} **${c.label}**`);
      lines.push(`   ${c.message}`);
      if (c.command) {
        lines.push(`   \`${c.command}\``);
      }
      if (c.evidence && c.evidence.length > 0) {
        for (const e of c.evidence) {
          lines.push(`   - ${e}`);
        }
      }
      lines.push(``);
    }
  }

  // Next steps
  if (report.nextSteps.length > 0) {
    lines.push(`## Next Steps`);
    lines.push(``);
    for (const step of report.nextSteps) {
      lines.push(`- [ ] ${step}`);
    }
    lines.push(``);
  }

  // Manual checklist
  const manualChecks = report.checks.filter((c) => c.status === "manual");
  if (manualChecks.length > 0) {
    lines.push(`## Manual Checklist`);
    lines.push(``);
    for (const c of manualChecks) {
      lines.push(`- [ ] **${c.label}** — ${c.message}`);
      if (c.command) {
        lines.push(`  \`${c.command}\``);
      }
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`*Generated by Prisom Project Panel — Sprint 53 Deployment Dry Run.*`);
  lines.push(`*No secrets are included in this report.*`);

  return lines.join("\n");
}
