import type {
  LaunchExecutionChecklist,
  LaunchExecutionStep,
  LaunchExecutionStatus,
} from "./launch-execution-types";

const PHASE_LABELS: Record<LaunchExecutionStep["phase"], string> = {
  freeze:     "Launch Freeze Confirmation",
  backup:     "Backup Confirmation",
  preflight:  "Preflight Checks",
  cutover:    "Cutover Execution",
  smoke:      "Smoke Tests",
  ecommerce:  "Ecommerce Verification",
  monitoring: "Post-Cutover Monitoring",
  handover:   "Client Handover",
  rollback:   "Rollback Contingency",
};

const PHASE_ORDER: LaunchExecutionStep["phase"][] = [
  "freeze", "backup", "preflight", "cutover", "smoke",
  "ecommerce", "monitoring", "handover", "rollback",
];

const STATUS_ICON: Record<LaunchExecutionStep["status"], string> = {
  pass:    "✅",
  warning: "⚠️",
  blocked: "🚫",
  manual:  "🔲",
  pending: "⏳",
};

const DECISION_LABELS: Record<LaunchExecutionStatus, string> = {
  not_started:  "Not Started",
  ready:        "🟢 READY TO LAUNCH",
  blocked:      "🔴 BLOCKED",
  in_progress:  "🟡 In Progress",
  complete:     "✅ Complete",
};

export function exportLaunchExecutionChecklist(checklist: LaunchExecutionChecklist): string {
  const lines: string[] = [
    "# LAUNCH_EXECUTION_CHECKLIST.md",
    "",
    `**Project:** ${checklist.projectId}`,
    `**Generated:** ${new Date(checklist.generatedAt).toUTCString()}`,
    `**Status:** ${DECISION_LABELS[checklist.status]}`,
    "",
    "> Read-only — launch execution documentation only. No production mutation.",
    "> All cutover commands must be executed manually by a named operator via SSH.",
    "",
    "---",
    "",
  ];

  if (checklist.blockers.length > 0) {
    lines.push("## ⛔ Blockers — Do Not Proceed", "");
    for (const b of checklist.blockers) lines.push(`- ${b}`);
    lines.push("");
  }

  if (checklist.warnings.length > 0) {
    lines.push("## ⚠️ Warnings", "");
    for (const w of checklist.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  lines.push("---", "", "## Go / No-Go Questions", "");
  for (const q of checklist.goNoGoQuestions) {
    lines.push(`- [ ] ${q}`);
  }
  lines.push("");

  lines.push("---", "", "## Evidence Checklist", "");
  for (const ev of checklist.evidenceChecklist) {
    lines.push(ev);
  }
  lines.push("");

  lines.push("---", "", "## Launch Execution Phases", "");

  for (const phase of PHASE_ORDER) {
    const phaseSteps = checklist.steps.filter((s) => s.phase === phase);
    if (phaseSteps.length === 0) continue;
    lines.push(`### ${PHASE_LABELS[phase]}`, "");
    for (const s of phaseSteps) {
      const icon = STATUS_ICON[s.status];
      lines.push(`#### ${icon} ${s.label}`);
      lines.push("");
      lines.push(s.description);
      if (s.operator) lines.push("", `**Operator:** ${s.operator}`);
      if (s.command) {
        lines.push("", "**Command (run manually on server):**", "```bash", s.command, "```");
      }
      if (s.evidence) lines.push("", `**Evidence:** ${s.evidence}`);
      if (s.safetyNote) lines.push("", `> **Safety:** ${s.safetyNote}`);
      lines.push("");
    }
  }

  lines.push("---", "", "## Operator Commands (run manually via SSH)", "");
  lines.push("```bash");
  for (const cmd of checklist.operatorCommands) lines.push(cmd);
  lines.push("```", "");

  lines.push("---", "", "## Smoke Commands", "");
  lines.push("```bash");
  for (const cmd of checklist.smokeCommands) lines.push(cmd);
  lines.push("```", "");

  lines.push("---", "", "## Rollback Commands", "");
  lines.push("```bash");
  for (const cmd of checklist.rollbackCommands) lines.push(cmd);
  lines.push("```", "");

  if (checklist.recommendedNextSteps.length > 0) {
    lines.push("---", "", "## Recommended Next Steps", "");
    for (const step of checklist.recommendedNextSteps) lines.push(`- ${step}`);
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "## Safety Notes",
    "",
    "- This checklist is read-only. No production mutation occurs from the panel.",
    "- All cutover commands must be executed manually by a named operator via SSH.",
    "- Do not restart any PM2 process from the panel.",
    "- Do not change DNS or nginx from the panel.",
    "- Sardar Security production must remain live throughout.",
    "- Doorsteps/LocalShop must not be touched.",
    "- No secrets are included in this export.",
    "",
    "---",
    "",
    "_Generated by Prisom Project Panel. Read-only — launch execution documentation only. No production mutation._",
    "",
  );

  return lines.join("\n");
}
