/**
 * lib/launch-freeze/launch-freeze-export.ts
 *
 * Sprint 75: Generates LAUNCH_FREEZE_CHECKLIST.md.
 * No secrets. No production mutation.
 */

import type {
  LaunchFreezeReport,
  LaunchFreezeCheck,
  LaunchFreezeCheckCategory,
} from "./launch-freeze-types";

const CATEGORY_LABELS: Record<LaunchFreezeCheckCategory, string> = {
  code:          "Code Changes",
  deployment:    "Deployment",
  database:      "Database",
  secrets:       "Secrets & Env Vars",
  routing:       "Routing & DNS",
  qa:            "QA Verification",
  team:          "Team",
  documentation: "Documentation",
  monitoring:    "Monitoring",
};

const CATEGORY_ORDER: LaunchFreezeCheckCategory[] = [
  "code", "deployment", "database", "secrets", "routing",
  "qa", "team", "documentation", "monitoring",
];

function statusIcon(status: LaunchFreezeCheck["status"]): string {
  switch (status) {
    case "pass":    return "✅";
    case "warning": return "⚠️";
    case "blocked": return "🔴";
    case "manual":  return "🔲";
    default:        return "⬜";
  }
}

function freezeStatusLabel(status: LaunchFreezeReport["status"]): string {
  switch (status) {
    case "frozen_pending_launch": return "🔒 FROZEN — PENDING LAUNCH";
    case "freeze_recommended":    return "🔵 FREEZE RECOMMENDED";
    case "blocked":               return "🔴 BLOCKED — CANNOT FREEZE";
    default:                      return "⬜ NOT FROZEN";
  }
}

export function exportLaunchFreezeReport(report: LaunchFreezeReport): string {
  const generatedAt = new Date(report.generatedAt).toUTCString();
  const sections: string[] = [];

  sections.push(`# Launch Freeze Checklist — Project ${report.projectId}

> Generated: ${generatedAt}
> This document is a read-only freeze checklist. No production mutation.

## Freeze Status

${freezeStatusLabel(report.status)}
`);

  if (report.blockers.length > 0) {
    sections.push(`## 🔴 Blockers\n\nResolve before entering freeze:\n\n${report.blockers.map((b) => `- ${b}`).join("\n")}\n`);
  }

  if (report.warnings.length > 0) {
    sections.push(`## ⚠️ Warnings\n\n${report.warnings.map((w) => `- ${w}`).join("\n")}\n`);
  }

  // Grouped checks
  sections.push("## Freeze Checklist\n");
  for (const cat of CATEGORY_ORDER) {
    const catChecks = report.checks.filter((c) => c.category === cat);
    if (catChecks.length === 0) continue;
    sections.push(`### ${CATEGORY_LABELS[cat]}\n`);
    for (const c of catChecks) {
      const req  = c.required ? " *(required)*" : " *(optional)*";
      const rule = c.freezeRule ? `\n  - Freeze rule: ${c.freezeRule}` : "";
      sections.push(`- ${statusIcon(c.status)} **${c.label}**${req}\n  ${c.description}${rule}\n`);
    }
  }

  // Allowed changes
  sections.push(`## ✅ Allowed Changes During Freeze\n\n${report.allowedChanges.map((c) => `- ${c}`).join("\n")}\n`);

  // Blocked changes
  sections.push(`## 🔴 Blocked Changes During Freeze\n\n${report.blockedChanges.map((c) => `- ${c}`).join("\n")}\n`);

  // Freeze rules
  if (report.freezeRules.length > 0) {
    sections.push(`## Freeze Rules\n\n${report.freezeRules.map((r) => `- ${r}`).join("\n")}\n`);
  }

  // Approval requirements
  sections.push(`## Changes Requiring Explicit Approval During Freeze

The following changes during the freeze window require written approval from the project owner:

- [ ] Any new deployment triggered after freeze begins
- [ ] Any secret value rotation
- [ ] Any dependency version bump
- [ ] Any change to nginx or PM2 configuration
- [ ] Any change that triggers a database migration
`);

  sections.push(`---
*Generated by Prisom Project Panel — Sprint 75. Read-only. No secrets included.*
`);

  return sections.join("\n");
}
