/**
 * lib/domains/nginx-ownership-scanner.ts
 *
 * Sprint 47: Read-only nginx ownership scanner.
 * Determines which project (if any) owns the nginx config for a given domain.
 *
 * Safety rules:
 *  - Read-only — never writes or modifies any config
 *  - Only reads from /etc/nginx/sites-available and /etc/nginx/sites-enabled
 *  - Filename validation: no path traversal
 *  - Returns configPath as basename only (no full FS paths to client)
 *  - Never returns raw config file contents
 *  - Panel domain is always protected
 *  - Doorstep/LocalShop configs are always protected
 */

import { promises as fs } from "fs";
import path               from "path";
import type { NginxOwnershipStatus } from "./domain-readiness-types";

const SITES_AVAILABLE = "/etc/nginx/sites-available";
const SITES_ENABLED   = "/etc/nginx/sites-enabled";
const MAX_FILE_BYTES  = 256_000;

// ── Protected domains / config identifiers ────────────────────────────────────

/** The panel domain must never be used as a project domain */
const PANEL_DOMAIN = "projects.doorstepmanchester.uk";

/** Patterns in config filenames or content that indicate protected Doorstep/LocalShop configs */
const PROTECTED_CONFIG_PATTERNS = [
  "doorstep",
  "localshop",
  "prisom-panel",
  "prisom-manager",
  "prisom-backend",
];

/** Comments written by Prisom's nginx generator that mark a managed config */
const PRISOM_MANAGED_MARKER = "managed-by: prisom-projects";
const PRISOM_PROJECT_ID_RE  = /^#\s*prisom-project-id:\s*([a-z0-9_\-]+)/im;
const PRISOM_PROJECT_SLUG_RE = /^#\s*prisom-project-slug:\s*([a-z0-9_\-]+)/im;
// Legacy marker from older Prisom releases
const PRISOM_LEGACY_MARKER  = "generated by prisom";

// ── File helpers ──────────────────────────────────────────────────────────────

function safeName(name: string): boolean {
  return !name.includes("/") && !name.includes("\\") && !name.includes("..");
}

async function listDir(dir: string): Promise<string[]> {
  try {
    return await fs.readdir(dir);
  } catch {
    return [];
  }
}

async function readConfigFile(dir: string, name: string): Promise<string | null> {
  if (!safeName(name)) return null;
  const filePath = path.join(dir, name);
  try {
    const buf = await fs.readFile(filePath);
    if (buf.length > MAX_FILE_BYTES) return null;
    return buf.toString("utf8");
  } catch {
    return null;
  }
}

/** Resolve a potential symlink to its real path basename. */
async function resolvedName(dir: string, name: string): Promise<string> {
  try {
    const real = await fs.realpath(path.join(dir, name));
    return path.basename(real);
  } catch {
    return name;
  }
}

// ── Nginx config parsers (no raw content returned to callers) ─────────────────

function matchesServerName(content: string, hostname: string): boolean {
  for (const line of content.split("\n")) {
    const t = line.trim();
    if (!t.startsWith("server_name")) continue;
    const names = t
      .replace(/^server_name\s+/, "")
      .replace(/;.*$/, "")
      .split(/\s+/);
    if (names.some((n) => n === hostname || n === `*.${hostname.split(".").slice(1).join(".")}`)) {
      return true;
    }
  }
  return false;
}

function extractProjectId(content: string): string | null {
  return content.match(PRISOM_PROJECT_ID_RE)?.[1] ?? null;
}

function extractProjectSlug(content: string): string | null {
  return content.match(PRISOM_PROJECT_SLUG_RE)?.[1] ?? null;
}

function isManagedByPrisom(content: string): boolean {
  const lower = content.toLowerCase();
  return lower.includes(PRISOM_MANAGED_MARKER) || lower.includes(PRISOM_LEGACY_MARKER);
}

function isProtectedConfigName(name: string): boolean {
  const lower = name.toLowerCase();
  return PROTECTED_CONFIG_PATTERNS.some((p) => lower.includes(p));
}

function isProtectedContent(content: string): boolean {
  const lower = content.toLowerCase();
  return PROTECTED_CONFIG_PATTERNS.some((p) => lower.includes(p)) ||
    lower.includes(PANEL_DOMAIN);
}

// ── Main scanner ──────────────────────────────────────────────────────────────

export type NginxScanInput = {
  domain:       string;
  projectId:    string;
  projectSlug?: string;
};

export async function scanNginxOwnership(
  input: NginxScanInput,
): Promise<NginxOwnershipStatus> {
  const { domain, projectId, projectSlug } = input;

  // Panel domain is always a protected blocker
  if (domain === PANEL_DOMAIN || domain.endsWith(`.${PANEL_DOMAIN}`)) {
    return {
      domain,
      managedByPrisom: false,
      protectedConfig:  true,
      conflict:         true,
      message:          "This domain is the Prisom Projects Panel domain and cannot be used as a project domain.",
    };
  }

  // Scan both directories, preferring sites-available for the canonical config
  const [availableNames, enabledNames] = await Promise.all([
    listDir(SITES_AVAILABLE),
    listDir(SITES_ENABLED),
  ]);

  // Build a map of config name → content, searching for the domain
  const allNames = Array.from(new Set([...availableNames, ...enabledNames]));

  for (const name of allNames) {
    if (!safeName(name)) continue;

    // Try sites-available first (canonical), then sites-enabled
    const content =
      (await readConfigFile(SITES_AVAILABLE, name)) ??
      (await readConfigFile(SITES_ENABLED,   name));
    if (!content) continue;

    if (!matchesServerName(content, domain)) continue;

    // Found a config that owns this domain
    const configBasename = name;

    // Check if this is a protected config
    if (isProtectedConfigName(name) || isProtectedContent(content)) {
      return {
        domain,
        configPath:      configBasename,
        managedByPrisom: false,
        protectedConfig: true,
        conflict:         true,
        message:          `Domain is claimed by a protected system config (${configBasename}). It cannot be used for a project.`,
      };
    }

    const managed     = isManagedByPrisom(content);
    const ownerProjId = extractProjectId(content);
    const ownerSlug   = extractProjectSlug(content);

    // Resolve enabled symlink if present
    let enabledBasename: string | undefined;
    if (enabledNames.includes(name)) {
      enabledBasename = await resolvedName(SITES_ENABLED, name);
    }

    // Config owned by a different project → conflict
    if (managed && ownerProjId && ownerProjId !== projectId) {
      return {
        domain,
        configPath:        configBasename,
        enabledPath:       enabledBasename,
        ownerProjectId:    ownerProjId,
        ownerProjectSlug:  ownerSlug,
        managedByPrisom:   true,
        protectedConfig:   false,
        conflict:          true,
        message:           `This domain's nginx config is managed by a different project (${ownerSlug ?? ownerProjId}). Check for conflicts before applying routes.`,
      };
    }

    // Config is managed by the same project or has no project marker → okay
    if (managed && (ownerProjId === projectId || !ownerProjId)) {
      return {
        domain,
        configPath:        configBasename,
        enabledPath:       enabledBasename,
        ownerProjectId:    ownerProjId ?? projectId,
        ownerProjectSlug:  ownerSlug ?? projectSlug,
        managedByPrisom:   true,
        protectedConfig:   false,
        conflict:          false,
        message:           "Nginx config is managed by this project.",
      };
    }

    // Config exists but is not Prisom-managed — unmanaged config owns this domain
    return {
      domain,
      configPath:      configBasename,
      enabledPath:     enabledBasename,
      managedByPrisom: false,
      protectedConfig: false,
      conflict:        true,
      message:         `An unmanaged nginx config (${configBasename}) already claims this domain. Review it before applying routes.`,
    };
  }

  // No config found for this domain
  return {
    domain,
    managedByPrisom: false,
    protectedConfig: false,
    conflict:        false,
    message:         "No nginx config found for this domain. Applying routes will create one.",
  };
}
