/**
 * lib/cutover-rehearsal/cutover-rehearsal-export.ts
 *
 * Sprint 75: Generates FINAL_CUTOVER_REHEARSAL.md.
 * No secrets. No production mutation.
 */

import type {
  CutoverRehearsalReport,
  CutoverRehearsalStep,
  CutoverRehearsalPhase,
} from "./cutover-rehearsal-types";

const PHASE_LABELS: Record<CutoverRehearsalPhase, string> = {
  pre_launch:  "Pre-Launch Checks",
  backup:      "Backup & Recovery",
  routing:     "Route Application",
  smoke_test:  "Smoke Tests",
  ecommerce:   "Ecommerce Checks",
  monitoring:  "Monitoring Setup",
  rollback:    "Rollback Readiness",
  handover:    "Client Handover",
};

const PHASE_ORDER: CutoverRehearsalPhase[] = [
  "pre_launch", "backup", "routing", "smoke_test",
  "ecommerce", "monitoring", "rollback", "handover",
];

function stepIcon(status: CutoverRehearsalStep["status"]): string {
  switch (status) {
    case "pass":    return "✅";
    case "warning": return "⚠️";
    case "blocked": return "🔴";
    case "manual":  return "🔲";
    default:        return "⬜";
  }
}

function overallLabel(status: CutoverRehearsalReport["status"]): string {
  switch (status) {
    case "ready_for_launch": return "✅ READY FOR LAUNCH";
    case "needs_review":     return "🔵 NEEDS REVIEW";
    case "blocked":          return "🔴 BLOCKED";
    default:                 return "⬜ NOT STARTED";
  }
}

export function exportCutoverRehearsalReport(report: CutoverRehearsalReport): string {
  const generatedAt = new Date(report.generatedAt).toUTCString();
  const sections: string[] = [];

  sections.push(`# Final Cutover Rehearsal — Project ${report.projectId}

> Generated: ${generatedAt}
> This document is a read-only rehearsal checklist. No production mutation.

## Overall Status

${overallLabel(report.status)}

| Item | Value |
|------|-------|
| Score | ${report.score}% of required steps passed |
| Blockers | ${report.blockers.length} |
| Warnings | ${report.warnings.length} |
`);

  if (report.blockers.length > 0) {
    sections.push(`## 🔴 Blockers\n\n${report.blockers.map((b) => `- ${b}`).join("\n")}\n`);
  }

  if (report.warnings.length > 0) {
    sections.push(`## ⚠️ Warnings\n\n${report.warnings.map((w) => `- ${w}`).join("\n")}\n`);
  }

  // Grouped steps
  sections.push("## Rehearsal Steps\n");
  for (const phase of PHASE_ORDER) {
    const phaseSteps = report.steps.filter((s) => s.phase === phase);
    if (phaseSteps.length === 0) continue;
    sections.push(`### ${PHASE_LABELS[phase]}\n`);
    for (const s of phaseSteps) {
      const req  = s.required ? " *(required)*" : " *(optional)*";
      const cmd  = s.command  ? `\n  - Command: \`${s.command}\`` : "";
      const evid = s.evidence ? `\n  - Evidence: \`${s.evidence}\`` : "";
      const note = s.safetyNote ? `\n  - ⚠️ ${s.safetyNote}` : "";
      sections.push(`- ${stepIcon(s.status)} **${s.label}**${req}\n  ${s.description}${cmd}${evid}${note}\n`);
    }
  }

  // Operator commands
  if (report.operatorCommands.length > 0) {
    sections.push(`## Operator Command Checklist\n\nRun these commands in order on launch day:\n\n\`\`\`bash\n${report.operatorCommands.map((c) => `# ${c}`).join("\n")}\n\`\`\`\n`);
  }

  // Rollback decision tree
  sections.push(`## Rollback Decision Tree\n\n${report.rollbackDecisionTree.map((l) => `- ${l}`).join("\n")}\n`);

  // Final go/no-go questions
  sections.push(`## Final Go / No-Go Questions\n\nAnswer YES to all before proceeding:\n\n${report.finalGoNoGoQuestions.map((q) => `- [ ] ${q}`).join("\n")}\n`);

  // Safety notes
  sections.push(`## Safety Notes

- Do NOT type APPLY PRODUCTION CUTOVER until all go/no-go questions are answered YES.
- Do NOT reload nginx without a passing \`sudo nginx -t\`.
- Do NOT restart PM2 from the panel UI — use server SSH only.
- Do NOT proceed if backup is older than 2 hours.
- Do NOT go live without a confirmed rollback plan.
- Keep client available during and immediately after cutover.
- Document the exact cutover time and operator name in the project Activity log.
`);

  sections.push(`---
*Generated by Prisom Project Panel — Sprint 75. Read-only. No secrets included.*
`);

  return sections.join("\n");
}
