import type {
  PostLaunchBugCaptureReport,
  PostLaunchIssueTemplate,
  PostLaunchIssueSeverity,
  PostLaunchIssueCategory,
} from "./post-launch-bug-types";

const SEVERITY_LABELS: Record<PostLaunchIssueSeverity, string> = {
  critical: "🚨 Critical",
  high:     "🔴 High",
  medium:   "🟡 Medium",
  low:      "🟢 Low",
  cosmetic: "⚪ Cosmetic",
};

const SEVERITY_ORDER: PostLaunchIssueSeverity[] = [
  "critical", "high", "medium", "low", "cosmetic",
];

const CATEGORY_LABELS: Record<PostLaunchIssueCategory, string> = {
  availability: "Availability",
  routing:      "Routing",
  checkout:     "Checkout",
  payments:     "Payments",
  orders:       "Orders",
  email:        "Email",
  admin:        "Admin",
  content:      "Content",
  performance:  "Performance",
  logs:         "Logs",
  unknown:      "Unknown",
};

export function exportPostLaunchBugCaptureReport(report: PostLaunchBugCaptureReport): string {
  const lines: string[] = [
    "# POST_LAUNCH_BUG_CAPTURE.md",
    "",
    `**Project:** ${report.projectId}`,
    `**Generated:** ${new Date(report.generatedAt).toUTCString()}`,
    "",
    "> Read-only — triage and evidence capture only. No production mutation.",
    "",
    "---",
    "",
  ];

  // Issue templates by severity
  lines.push("## Issue Templates", "");

  for (const severity of SEVERITY_ORDER) {
    const templates = report.issueTemplates.filter((t) => t.severity === severity);
    if (templates.length === 0) continue;
    lines.push(`### ${SEVERITY_LABELS[severity]}`, "");
    for (const tpl of templates) {
      lines.push(`#### ${tpl.title}`);
      lines.push("", `**Category:** ${CATEGORY_LABELS[tpl.category]}`);
      lines.push("", tpl.description);

      lines.push("", "**Evidence to collect:**");
      for (const ev of tpl.evidenceToCollect) lines.push(`- ${ev}`);

      lines.push("", "**Immediate checks:**", "```bash");
      for (const chk of tpl.immediateChecks) lines.push(chk);
      lines.push("```");

      lines.push("", `**Escalation rule:** ${tpl.escalationRule}`, "");
    }
  }

  // Triage rules
  lines.push("---", "", "## Triage Rules", "");
  for (const rule of report.triageRules) lines.push(`- ${rule}`);
  lines.push("");

  // Immediate fix allowed
  lines.push("---", "", "## Allowed Immediate Fixes", "");
  for (const item of report.immediateFixAllowed) lines.push(`- ${item}`);
  lines.push("");

  // Changes requiring approval
  lines.push("---", "", "## Changes Requiring Operator Approval", "");
  for (const item of report.changesRequiringApproval) lines.push(`- [ ] ${item}`);
  lines.push("");

  // Next steps
  if (report.recommendedNextSteps.length > 0) {
    lines.push("---", "", "## Recommended Next Steps", "");
    for (const step of report.recommendedNextSteps) lines.push(`- ${step}`);
    lines.push("");
  }

  // Issue log table
  lines.push(
    "---",
    "",
    "## Issue Log",
    "",
    "> Record issues discovered post-launch here.",
    "",
    "| Time | Severity | Category | Description | Evidence | Resolution |",
    "| --- | --- | --- | --- | --- | --- |",
    "| | | | | | |",
    "| | | | | | |",
    "",
    "---",
    "",
    "_Generated by Prisom Project Panel. Read-only — no production mutation._",
    "",
  );

  return lines.join("\n");
}
