/**
 * lib/projects/nginx-manager.ts
 *
 * Safe Nginx config generation and domain publishing for Prisom projects.
 *
 * Route modes:
 *   fullstack_node  — all routes proxy to backend (default)
 *   static_plus_api — nginx serves static root, <apiPrefix> proxies to backend
 *   static_only     — nginx serves static files only (no backend)
 *   api_only        — all routes proxy to backend (same as fullstack_node)
 *
 * Security rules:
 *   - Domain names are validated against a strict regex before use
 *   - Config written with fs.writeFile (no shell)
 *   - Symlink created with fs.symlink (no shell)
 *   - nginx -t, systemctl reload, certbot run with execFile (no shell)
 *   - Port must come from the DB (validated to be in range 4100–4999)
 *   - Never runs as root — returns clear permission error messages
 *
 * Nginx layout:
 *   /etc/nginx/sites-available/<domain>.conf
 *   /etc/nginx/sites-enabled/<domain>.conf  (symlink)
 */

import path from "path";
import { promises as fs } from "fs";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

// ── Constants ──────────────────────────────────────────────────────────────

const NGINX_SITES_AVAILABLE = "/etc/nginx/sites-available";
const NGINX_SITES_ENABLED   = "/etc/nginx/sites-enabled";

const RESERVED_HOSTNAMES = new Set([
  "projects.doorstepmanchester.uk",
  "doorstepmanchester.uk",
  "www.doorstepmanchester.uk",
  "178.105.105.59",
  "localhost",
  "127.0.0.1",
]);

function normalizeHostname(hostname: string): string {
  return hostname.trim().toLowerCase().replace(/^https?:\/\//, "").replace(/\/.*$/, "");
}

export function isReservedHostname(hostname: string): boolean {
  const clean = normalizeHostname(hostname);

  if (RESERVED_HOSTNAMES.has(clean)) return true;

  // Block bare IPv4 addresses from being used as custom domains.
  if (/^(?:\d{1,3}\.){3}\d{1,3}$/.test(clean)) return true;

  return false;
}

export function assertPublishableHostname(hostname: string): { ok: true } | { ok: false; error: string } {
  const clean = normalizeHostname(hostname);

  if (isReservedHostname(clean)) {
    return {
      ok: false,
      error: `${clean} is a reserved control hostname and cannot be used as a project domain.`,
    };
  }

  return { ok: true };
}

// IP preview — per-project location blocks included into a shared server block
const NGINX_IP_PREVIEW_LOCATIONS = "/etc/nginx/prisom-project-locations";
const NGINX_IP_PREVIEW_CONF      = "/etc/nginx/sites-available/prisom-ip-preview.conf";
const NGINX_IP_PREVIEW_ENABLED   = "/etc/nginx/sites-enabled/prisom-ip-preview.conf";

export type RouteMode =
  | "fullstack_node"
  | "static_plus_api"
  | "static_only"
  | "api_only";

// ── Domain validation ──────────────────────────────────────────────────────

const DOMAIN_RE =
  /^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

export function isValidDomain(hostname: string): boolean {
  if (!hostname || hostname.length < 4 || hostname.length > 253) return false;
  if (hostname.includes("..") || hostname.includes("/") || hostname.includes("\\"))
    return false;
  return DOMAIN_RE.test(hostname);
}

// ── Config generation ──────────────────────────────────────────────────────

/** Shared proxy location block snippet (WebSocket-compatible). */
function proxyLocation(prefix: string, port: number): string {
  return (
    `    location ${prefix} {\n` +
    `        proxy_pass         http://127.0.0.1:${port};\n` +
    `        proxy_http_version 1.1;\n` +
    `        proxy_set_header   Upgrade           $http_upgrade;\n` +
    `        proxy_set_header   Connection        'upgrade';\n` +
    `        proxy_set_header   Host              $host;\n` +
    `        proxy_set_header   X-Real-IP         $remote_addr;\n` +
    `        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\n` +
    `        proxy_set_header   X-Forwarded-Proto $scheme;\n` +
    `        proxy_cache_bypass $http_upgrade;\n` +
    `    }\n`
  );
}

export interface NginxConfigOptions {
  hostname:        string;
  port:            number;
  routeMode?:      RouteMode;
  /** Absolute path to the static frontend files (for static_plus_api / static_only). */
  staticRoot?:     string;
  /** API prefix (default "/api") for static_plus_api mode. */
  apiPrefix?:      string;
}

/**
 * Generates a complete nginx HTTP server block for the given options.
 * Supports all four route modes.
 */
export function generateNginxConfig(opts: NginxConfigOptions): string {
  const { hostname, port } = opts;
  const mode      = opts.routeMode  ?? "fullstack_node";
  const apiPrefix = (opts.apiPrefix ?? "/api").replace(/\/*$/, "/"); // ensure trailing slash
  const staticRoot = opts.staticRoot ?? "";

  const header =
    `# Prisom project — ${hostname} [${mode}]\n` +
    `# Auto-generated by Prisom Project Panel. Manual edits will be overwritten.\n`;

  const serverOpen =
    `server {\n` +
    `    listen 80;\n` +
    `    server_name ${hostname};\n\n`;

  const serverClose = `}\n`;

  switch (mode) {
    case "fullstack_node":
    case "api_only":
      return header + serverOpen + proxyLocation("/", port) + serverClose;

    case "static_plus_api":
      if (!staticRoot) {
        // Fall back to fullstack if no static root provided
        return header + serverOpen + proxyLocation("/", port) + serverClose;
      }
      return (
        header +
        serverOpen +
        `    root ${staticRoot};\n` +
        `    index index.html;\n\n` +
        proxyLocation(apiPrefix, port) +
        `\n` +
        `    location / {\n` +
        `        try_files $uri $uri/ /index.html;\n` +
        `    }\n` +
        serverClose
      );

    case "static_only":
      if (!staticRoot) {
        return header + serverOpen + proxyLocation("/", port) + serverClose;
      }
      return (
        header +
        serverOpen +
        `    root ${staticRoot};\n` +
        `    index index.html;\n\n` +
        `    location / {\n` +
        `        try_files $uri $uri/ /index.html;\n` +
        `    }\n` +
        serverClose
      );
  }
}

// ── Result types ───────────────────────────────────────────────────────────

export interface NginxPublishResult {
  ok:          boolean;
  error?:      string;
  configPath?: string;
}

export interface SslIssueResult {
  ok:    boolean;
  error?: string;
  logs?: string;
}

// ── Permission error helper ────────────────────────────────────────────────

function permError(path_: string, dir: string): string {
  const user = process.env.USER ?? "prisom";
  return (
    `Permission denied: cannot write to ${path_}.\n` +
    `Fix with:\n` +
    `  sudo mkdir -p ${dir}\n` +
    `  sudo chown ${user}:${user} ${dir}`
  );
}

// ── Domain publishing ──────────────────────────────────────────────────────

/**
 * Writes an nginx config, creates the sites-enabled symlink, tests, and reloads.
 *
 * `port` MUST come from the DB — never pass a user-supplied port.
 */
export async function publishDomain(
  hostname: string,
  port: number,
  opts?: Omit<NginxConfigOptions, "hostname" | "port">
): Promise<NginxPublishResult> {
  if (!isValidDomain(hostname)) {
    return { ok: false, error: `Invalid domain name: "${hostname}"` };
  }
  if (!Number.isInteger(port) || port < 4100 || port > 4999) {
    return {
      ok: false,
      error: `Port ${port} is outside the allowed range (4100–4999).`,
    };
  }

  const configFilename = `${hostname}.conf`;
  const configPath     = path.join(NGINX_SITES_AVAILABLE, configFilename);
  const enabledPath    = path.join(NGINX_SITES_ENABLED,   configFilename);
  const configContent  = generateNginxConfig({ hostname, port, ...opts });

  // Ensure sites-available directory is writable
  try {
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM")
      return { ok: false, error: permError(NGINX_SITES_AVAILABLE, NGINX_SITES_AVAILABLE) };
    return { ok: false, error: `Cannot create nginx directory: ${(e as Error).message}` };
  }

  // Write config
  try {
    await fs.writeFile(configPath, configContent, { encoding: "utf8", flag: "w" });
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM")
      return { ok: false, error: permError(configPath, NGINX_SITES_AVAILABLE) };
    return { ok: false, error: `Failed to write nginx config: ${(e as Error).message}` };
  }

  // Create/replace symlink in sites-enabled
  try {
    await fs.unlink(enabledPath).catch(() => {});
    await fs.symlink(configPath, enabledPath);
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM")
      return { ok: false, error: permError(enabledPath, NGINX_SITES_ENABLED) };
    return { ok: false, error: `Failed to create nginx symlink: ${(e as Error).message}` };
  }

  // Test nginx config
  try {
    await execFileAsync("sudo", ["-n", "/usr/sbin/nginx", "-t"], { timeout: 10_000 });
  } catch (e) {
    await fs.unlink(enabledPath).catch(() => {});
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return { ok: false, error: `nginx config test failed:\n${msg}` };
  }

  // Reload nginx
  try {
    await execFileAsync("sudo", ["-n", "/bin/systemctl", "reload", "nginx"], { timeout: 15_000 });
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return {
      ok: false,
      error:
        `Config written and tested, but nginx reload failed: ${msg}\n` +
        `Reload manually: sudo systemctl reload nginx`,
    };
  }

  return { ok: true, configPath };
}

// ── IP preview (path-based) ────────────────────────────────────────────────

export interface IpPreviewResult {
  ok:    boolean;
  error?: string;
  url?:  string;
  mode?: "path_ip";
}

/**
 * Writes a per-project nginx location block and (re)creates the shared
 * IP-preview server block that includes all project locations.
 *
 * URL shape: http://<serverIp>/<slug>/
 *
 * All nginx ops are non-fatal from the caller's perspective — the caller
 * should record the error but must NOT fail the whole deployment.
 */
export async function publishIpPreviewPath(
  slug:     string,
  port:     number,
  opts?: {
    routeMode?:  RouteMode;
    staticRoot?: string;
    apiPrefix?:  string;
    serverIp?:   string;
  }
): Promise<IpPreviewResult> {
  if (!Number.isInteger(port) || port < 4100 || port > 4999) {
    return { ok: false, error: `Port ${port} is outside the allowed range (4100–4999).` };
  }

  const serverIp  = opts?.serverIp  ?? process.env.VPS_IP ?? "178.105.105.59";
  // Sanitise slug to a safe nginx path token
  const slugSafe  = slug.replace(/[^a-z0-9-]/gi, "-").toLowerCase();
  const prefix    = `/${slugSafe}`;
  const url       = `http://${serverIp}${prefix}/`;
  const mode      = opts?.routeMode ?? "fullstack_node";
  const apiPrefix = (opts?.apiPrefix ?? "/api").replace(/\/+$/, "");

  // ── Build location block ─────────────────────────────────────────────────

  const proxyBlock = (locPrefix: string, proxyPort: number) =>
    `location ${locPrefix}/ {\n` +
    `    proxy_pass         http://127.0.0.1:${proxyPort}/;\n` +
    `    proxy_http_version 1.1;\n` +
    `    proxy_set_header   Upgrade           $http_upgrade;\n` +
    `    proxy_set_header   Connection        'upgrade';\n` +
    `    proxy_set_header   Host              $host;\n` +
    `    proxy_set_header   X-Real-IP         $remote_addr;\n` +
    `    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\n` +
    `    proxy_set_header   X-Forwarded-Proto $scheme;\n` +
    `    proxy_cache_bypass $http_upgrade;\n` +
    `}\n`;

  let locationContent = `# Prisom project — ${slug} [${mode}] — auto-generated\n`;

  if ((mode === "static_only" || mode === "static_plus_api") && opts?.staticRoot) {
    // Serve static files via alias; alias must end with /
    locationContent +=
      `location ${prefix}/ {\n` +
      `    alias     ${opts.staticRoot}/;\n` +
      `    try_files $uri $uri/ ${prefix}/index.html;\n` +
      `}\n`;
    if (mode === "static_plus_api") {
      locationContent += proxyBlock(`${prefix}${apiPrefix}`, port);
    }
  } else {
    // fullstack_node / api_only — proxy everything at this path
    locationContent += proxyBlock(prefix, port);
  }

  // ── Ensure locations directory ───────────────────────────────────────────

  try {
    await fs.mkdir(NGINX_IP_PREVIEW_LOCATIONS, { recursive: true });
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM") {
      return {
        ok: false,
        error: permError(NGINX_IP_PREVIEW_LOCATIONS, NGINX_IP_PREVIEW_LOCATIONS),
      };
    }
    return { ok: false, error: `Cannot create locations dir: ${(e as Error).message}` };
  }

  // ── Write per-project location block ────────────────────────────────────

  const locPath = path.join(NGINX_IP_PREVIEW_LOCATIONS, `${slugSafe}.conf`);
  try {
    await fs.writeFile(locPath, locationContent, { encoding: "utf8", flag: "w" });
  } catch (e) {
    return { ok: false, error: `Cannot write location block: ${(e as Error).message}` };
  }

  // ── Ensure shared IP preview server block ────────────────────────────────

  const serverBlockContent =
    `# Prisom IP preview server — auto-managed by Prisom Project Panel.\n` +
    `# Do not edit manually; changes will be overwritten on next deploy.\n` +
    `server {\n` +
    `    listen 80;\n` +
    `    server_name ${serverIp};\n\n` +
    `    # Per-project path-based location blocks (auto-included)\n` +
    `    include ${NGINX_IP_PREVIEW_LOCATIONS}/*.conf;\n\n` +
    `    location / {\n` +
    `        return 404 "No Prisom project at this path.";\n` +
    `    }\n` +
    `}\n`;

  try {
    await fs.mkdir(path.dirname(NGINX_IP_PREVIEW_CONF), { recursive: true });
    await fs.writeFile(NGINX_IP_PREVIEW_CONF, serverBlockContent, { encoding: "utf8", flag: "w" });
  } catch (e) {
    return { ok: false, error: `Cannot write IP preview server block: ${(e as Error).message}` };
  }

  // Symlink in sites-enabled (idempotent)
  try {
    await fs.unlink(NGINX_IP_PREVIEW_ENABLED).catch(() => {});
    await fs.symlink(NGINX_IP_PREVIEW_CONF, NGINX_IP_PREVIEW_ENABLED);
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM") {
      return { ok: false, error: permError(NGINX_IP_PREVIEW_ENABLED, NGINX_SITES_ENABLED) };
    }
    return { ok: false, error: `Cannot create IP preview symlink: ${(e as Error).message}` };
  }

  // ── Test + reload ────────────────────────────────────────────────────────

  try {
    await execFileAsync("sudo", ["-n", "/usr/sbin/nginx", "-t"], { timeout: 10_000 });
  } catch (e) {
    // Roll back location file so subsequent nginx starts aren't broken
    await fs.unlink(locPath).catch(() => {});
    const stderr = (e as { stderr?: string }).stderr ?? "";
    return { ok: false, error: `nginx config test failed:\n${stderr.trim() || (e instanceof Error ? e.message : String(e))}` };
  }

  try {
    await execFileAsync("sudo", ["-n", "/bin/systemctl", "reload", "nginx"], { timeout: 15_000 });
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    return {
      ok: false,
      error: `Config written, but nginx reload failed: ${stderr.trim() || (e instanceof Error ? e.message : String(e))}`,
    };
  }

  return { ok: true, url, mode: "path_ip" };
}

// ── DNS verification ──────────────────────────────────────────────────────

export interface DnsVerifyResult {
  ok:          boolean;
  resolvedIp?: string;
  error?:      string;
}

/**
 * Verifies that `hostname` has a DNS A record pointing to `expectedIp`.
 * Uses Node's `dns.resolve4()` — bypasses OS resolver cache for a fresh result.
 */
export async function verifyDnsARecord(
  hostname:   string,
  expectedIp: string
): Promise<DnsVerifyResult> {
  const { resolve4 } = await import("dns/promises");
  try {
    const addresses = await resolve4(hostname);
    if (addresses.includes(expectedIp)) {
      return { ok: true, resolvedIp: addresses[0] };
    }
    return {
      ok:         false,
      resolvedIp: addresses[0],
      error:      `DNS resolves to ${addresses.join(", ")} — expected ${expectedIp}`,
    };
  } catch (e) {
    const err = e as NodeJS.ErrnoException;
    if (
      err.code === "ENOTFOUND" ||
      err.code === "ENODATA"   ||
      err.code === "ESERVFAIL"
    ) {
      return {
        ok:    false,
        error: "No DNS A record found — add an A record pointing to your server first",
      };
    }
    return { ok: false, error: `DNS lookup failed: ${err.message}` };
  }
}

// ── Nginx config removal ───────────────────────────────────────────────────

export interface NginxRemoveResult {
  ok:     boolean;
  error?: string;
}

/**
 * Removes the nginx config file and sites-enabled symlink for a published domain,
 * then tests and reloads nginx.
 *
 * File removal is best-effort (non-fatal if files are already gone).
 */
export async function removeDomainNginxConfig(
  hostname: string
): Promise<NginxRemoveResult> {
  if (!isValidDomain(hostname)) {
    return { ok: false, error: `Invalid domain name: "${hostname}"` };
  }

  const configFilename = `${hostname}.conf`;
  const configPath     = path.join(NGINX_SITES_AVAILABLE, configFilename);
  const enabledPath    = path.join(NGINX_SITES_ENABLED,   configFilename);

  // Remove symlink and config (ignore ENOENT — already gone is fine)
  await fs.unlink(enabledPath).catch(() => {});
  await fs.unlink(configPath).catch(() => {});

  // Test nginx config (must pass before reload)
  try {
    await execFileAsync("sudo", ["-n", "/usr/sbin/nginx", "-t"], { timeout: 10_000 });
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return { ok: false, error: `nginx config test failed after removal:\n${msg}` };
  }

  // Reload nginx
  try {
    await execFileAsync("sudo", ["-n", "/bin/systemctl", "reload", "nginx"], { timeout: 15_000 });
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return { ok: false, error: `nginx reload failed after removal: ${msg}` };
  }

  return { ok: true };
}

// ── SSL via certbot ────────────────────────────────────────────────────────

/**
 * Issues an SSL certificate for `hostname` using certbot --nginx.
 * Requires certbot to be installed and nginx to already be serving HTTP on 80.
 *
 * This function runs `certbot --nginx -d <hostname> --non-interactive --agree-tos
 *   --email <email>` via execFile — no shell.
 */
export async function issueSslCertificate(
  hostname: string,
  email: string
): Promise<SslIssueResult> {
  if (!isValidDomain(hostname)) {
    return { ok: false, error: `Invalid domain name: "${hostname}"` };
  }
  if (!email || !email.includes("@")) {
    return { ok: false, error: "A valid email address is required for certbot." };
  }

  // Check certbot is installed
  try {
    await execFileAsync("which", ["certbot"], { timeout: 5_000 });
  } catch {
    return {
      ok: false,
      error:
        "certbot not found. Install with:\n" +
        "  sudo apt-get install certbot python3-certbot-nginx\n" +
        `Then run: sudo certbot --nginx -d ${hostname}`,
    };
  }

  try {
    const { stdout, stderr } = await execFileAsync(
      "certbot",
      [
        "--nginx",
        "-d", hostname,
        "--non-interactive",
        "--agree-tos",
        "--email", email,
        "--redirect",
      ],
      { timeout: 120_000 }
    );
    const logs = [stdout, stderr].filter(Boolean).join("\n").trim();
    return { ok: true, logs };
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return {
      ok: false,
      error: `certbot failed: ${msg}`,
      logs:  msg,
    };
  }
}
