/**
 * lib/projects/nginx-manager.ts
 *
 * Safe Nginx config generation and domain publishing for Prisom projects.
 *
 * Route modes:
 *   fullstack_node  — all routes proxy to backend (default)
 *   static_plus_api — nginx serves static root, <apiPrefix> proxies to backend
 *   static_only     — nginx serves static files only (no backend)
 *   api_only        — all routes proxy to backend (same as fullstack_node)
 *
 * Security rules:
 *   - Domain names are validated against a strict regex before use
 *   - Config written with fs.writeFile (no shell)
 *   - Symlink created with fs.symlink (no shell)
 *   - nginx -t, systemctl reload, certbot run with execFile (no shell)
 *   - Port must come from the DB (validated to be in range 4100–4999)
 *   - Never runs as root — returns clear permission error messages
 *
 * Nginx layout:
 *   /etc/nginx/sites-available/prisom-projects/<domain>.conf
 *   /etc/nginx/sites-enabled/<domain>.conf  (symlink)
 */

import path from "path";
import { promises as fs } from "fs";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

// ── Constants ──────────────────────────────────────────────────────────────

const NGINX_SITES_AVAILABLE = "/etc/nginx/sites-available/prisom-projects";
const NGINX_SITES_ENABLED   = "/etc/nginx/sites-enabled";

export type RouteMode =
  | "fullstack_node"
  | "static_plus_api"
  | "static_only"
  | "api_only";

// ── Domain validation ──────────────────────────────────────────────────────

const DOMAIN_RE =
  /^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

export function isValidDomain(hostname: string): boolean {
  if (!hostname || hostname.length < 4 || hostname.length > 253) return false;
  if (hostname.includes("..") || hostname.includes("/") || hostname.includes("\\"))
    return false;
  return DOMAIN_RE.test(hostname);
}

// ── Config generation ──────────────────────────────────────────────────────

/** Shared proxy location block snippet (WebSocket-compatible). */
function proxyLocation(prefix: string, port: number): string {
  return (
    `    location ${prefix} {\n` +
    `        proxy_pass         http://127.0.0.1:${port};\n` +
    `        proxy_http_version 1.1;\n` +
    `        proxy_set_header   Upgrade           $http_upgrade;\n` +
    `        proxy_set_header   Connection        'upgrade';\n` +
    `        proxy_set_header   Host              $host;\n` +
    `        proxy_set_header   X-Real-IP         $remote_addr;\n` +
    `        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\n` +
    `        proxy_set_header   X-Forwarded-Proto $scheme;\n` +
    `        proxy_cache_bypass $http_upgrade;\n` +
    `    }\n`
  );
}

export interface NginxConfigOptions {
  hostname:        string;
  port:            number;
  routeMode?:      RouteMode;
  /** Absolute path to the static frontend files (for static_plus_api / static_only). */
  staticRoot?:     string;
  /** API prefix (default "/api") for static_plus_api mode. */
  apiPrefix?:      string;
}

/**
 * Generates a complete nginx HTTP server block for the given options.
 * Supports all four route modes.
 */
export function generateNginxConfig(opts: NginxConfigOptions): string {
  const { hostname, port } = opts;
  const mode      = opts.routeMode  ?? "fullstack_node";
  const apiPrefix = (opts.apiPrefix ?? "/api").replace(/\/*$/, "/"); // ensure trailing slash
  const staticRoot = opts.staticRoot ?? "";

  const header =
    `# Prisom project — ${hostname} [${mode}]\n` +
    `# Auto-generated by Prisom Project Panel. Manual edits will be overwritten.\n`;

  const serverOpen =
    `server {\n` +
    `    listen 80;\n` +
    `    server_name ${hostname};\n\n`;

  const serverClose = `}\n`;

  switch (mode) {
    case "fullstack_node":
    case "api_only":
      return header + serverOpen + proxyLocation("/", port) + serverClose;

    case "static_plus_api":
      if (!staticRoot) {
        // Fall back to fullstack if no static root provided
        return header + serverOpen + proxyLocation("/", port) + serverClose;
      }
      return (
        header +
        serverOpen +
        `    root ${staticRoot};\n` +
        `    index index.html;\n\n` +
        proxyLocation(apiPrefix, port) +
        `\n` +
        `    location / {\n` +
        `        try_files $uri $uri/ /index.html;\n` +
        `    }\n` +
        serverClose
      );

    case "static_only":
      if (!staticRoot) {
        return header + serverOpen + proxyLocation("/", port) + serverClose;
      }
      return (
        header +
        serverOpen +
        `    root ${staticRoot};\n` +
        `    index index.html;\n\n` +
        `    location / {\n` +
        `        try_files $uri $uri/ /index.html;\n` +
        `    }\n` +
        serverClose
      );
  }
}

// ── Result types ───────────────────────────────────────────────────────────

export interface NginxPublishResult {
  ok:          boolean;
  error?:      string;
  configPath?: string;
}

export interface SslIssueResult {
  ok:    boolean;
  error?: string;
  logs?: string;
}

// ── Permission error helper ────────────────────────────────────────────────

function permError(path_: string, dir: string): string {
  const user = process.env.USER ?? "prisom";
  return (
    `Permission denied: cannot write to ${path_}.\n` +
    `Fix with:\n` +
    `  sudo mkdir -p ${dir}\n` +
    `  sudo chown ${user}:${user} ${dir}`
  );
}

// ── Domain publishing ──────────────────────────────────────────────────────

/**
 * Writes an nginx config, creates the sites-enabled symlink, tests, and reloads.
 *
 * `port` MUST come from the DB — never pass a user-supplied port.
 */
export async function publishDomain(
  hostname: string,
  port: number,
  opts?: Omit<NginxConfigOptions, "hostname" | "port">
): Promise<NginxPublishResult> {
  if (!isValidDomain(hostname)) {
    return { ok: false, error: `Invalid domain name: "${hostname}"` };
  }
  if (!Number.isInteger(port) || port < 4100 || port > 4999) {
    return {
      ok: false,
      error: `Port ${port} is outside the allowed range (4100–4999).`,
    };
  }

  const configFilename = `${hostname}.conf`;
  const configPath     = path.join(NGINX_SITES_AVAILABLE, configFilename);
  const enabledPath    = path.join(NGINX_SITES_ENABLED,   configFilename);
  const configContent  = generateNginxConfig({ hostname, port, ...opts });

  // Ensure sites-available/prisom-projects directory exists
  try {
    await fs.mkdir(NGINX_SITES_AVAILABLE, { recursive: true });
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM")
      return { ok: false, error: permError(NGINX_SITES_AVAILABLE, NGINX_SITES_AVAILABLE) };
    return { ok: false, error: `Cannot create nginx directory: ${(e as Error).message}` };
  }

  // Write config
  try {
    await fs.writeFile(configPath, configContent, { encoding: "utf8", flag: "w" });
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM")
      return { ok: false, error: permError(configPath, NGINX_SITES_AVAILABLE) };
    return { ok: false, error: `Failed to write nginx config: ${(e as Error).message}` };
  }

  // Create/replace symlink in sites-enabled
  try {
    await fs.unlink(enabledPath).catch(() => {});
    await fs.symlink(configPath, enabledPath);
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM")
      return { ok: false, error: permError(enabledPath, NGINX_SITES_ENABLED) };
    return { ok: false, error: `Failed to create nginx symlink: ${(e as Error).message}` };
  }

  // Test nginx config
  try {
    await execFileAsync("nginx", ["-t"], { timeout: 10_000 });
  } catch (e) {
    await fs.unlink(enabledPath).catch(() => {});
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return { ok: false, error: `nginx config test failed:\n${msg}` };
  }

  // Reload nginx
  try {
    await execFileAsync("systemctl", ["reload", "nginx"], { timeout: 15_000 });
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return {
      ok: false,
      error:
        `Config written and tested, but nginx reload failed: ${msg}\n` +
        `Reload manually: sudo systemctl reload nginx`,
    };
  }

  return { ok: true, configPath };
}

// ── SSL via certbot ────────────────────────────────────────────────────────

/**
 * Issues an SSL certificate for `hostname` using certbot --nginx.
 * Requires certbot to be installed and nginx to already be serving HTTP on 80.
 *
 * This function runs `certbot --nginx -d <hostname> --non-interactive --agree-tos
 *   --email <email>` via execFile — no shell.
 */
export async function issueSslCertificate(
  hostname: string,
  email: string
): Promise<SslIssueResult> {
  if (!isValidDomain(hostname)) {
    return { ok: false, error: `Invalid domain name: "${hostname}"` };
  }
  if (!email || !email.includes("@")) {
    return { ok: false, error: "A valid email address is required for certbot." };
  }

  // Check certbot is installed
  try {
    await execFileAsync("which", ["certbot"], { timeout: 5_000 });
  } catch {
    return {
      ok: false,
      error:
        "certbot not found. Install with:\n" +
        "  sudo apt-get install certbot python3-certbot-nginx\n" +
        `Then run: sudo certbot --nginx -d ${hostname}`,
    };
  }

  try {
    const { stdout, stderr } = await execFileAsync(
      "certbot",
      [
        "--nginx",
        "-d", hostname,
        "--non-interactive",
        "--agree-tos",
        "--email", email,
        "--redirect",
      ],
      { timeout: 120_000 }
    );
    const logs = [stdout, stderr].filter(Boolean).join("\n").trim();
    return { ok: true, logs };
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return {
      ok: false,
      error: `certbot failed: ${msg}`,
      logs:  msg,
    };
  }
}
