/**
 * lib/projects/nginx-manager.ts
 *
 * Safe Nginx config generation and domain publishing for Prisom projects.
 *
 * Security rules:
 *   - Domain names are validated against a strict regex before use
 *   - Config is written with fs.writeFile (no shell)
 *   - Symlink is created with fs.symlink (no shell)
 *   - nginx -t and systemctl reload are run with execFile (no shell)
 *   - Port must come from the DB (validated to be in range 4100–4999)
 *   - Never runs as root — if permission is denied, returns a clear error
 *
 * Nginx layout assumed on the VPS:
 *   /etc/nginx/sites-available/prisom-projects/<domain>.conf
 *   /etc/nginx/sites-enabled/<domain>.conf  (symlink)
 */

import path from "path";
import { promises as fs } from "fs";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);

// ── Paths ──────────────────────────────────────────────────────────────────

const NGINX_SITES_AVAILABLE = "/etc/nginx/sites-available/prisom-projects";
const NGINX_SITES_ENABLED   = "/etc/nginx/sites-enabled";

// ── Domain validation ──────────────────────────────────────────────────────

/**
 * Validates a domain/hostname string.
 *   - Letters, digits, hyphens, and dots only
 *   - No leading/trailing dots or hyphens
 *   - No double dots (path traversal)
 *   - Must be at least 4 chars (a.bc)
 *   - Max 253 chars (DNS limit)
 */
const DOMAIN_RE = /^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

export function isValidDomain(hostname: string): boolean {
  if (!hostname || hostname.length < 4 || hostname.length > 253) return false;
  if (hostname.includes("..")) return false;
  if (hostname.includes("/") || hostname.includes("\\")) return false;
  return DOMAIN_RE.test(hostname);
}

// ── Config generation ──────────────────────────────────────────────────────

/**
 * Generates a minimal but correct nginx HTTP reverse-proxy config.
 * WebSocket-compatible (Upgrade header forwarded).
 */
export function generateNginxConfig(hostname: string, port: number): string {
  return (
    `# Prisom project — ${hostname}\n` +
    `# Auto-generated by Prisom Project Panel. Manual edits will be overwritten.\n` +
    `server {\n` +
    `    listen 80;\n` +
    `    server_name ${hostname};\n` +
    `\n` +
    `    location / {\n` +
    `        proxy_pass         http://127.0.0.1:${port};\n` +
    `        proxy_http_version 1.1;\n` +
    `        proxy_set_header   Upgrade           $http_upgrade;\n` +
    `        proxy_set_header   Connection        'upgrade';\n` +
    `        proxy_set_header   Host              $host;\n` +
    `        proxy_set_header   X-Real-IP         $remote_addr;\n` +
    `        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;\n` +
    `        proxy_set_header   X-Forwarded-Proto $scheme;\n` +
    `        proxy_cache_bypass $http_upgrade;\n` +
    `    }\n` +
    `}\n`
  );
}

// ── Result type ────────────────────────────────────────────────────────────

export interface NginxPublishResult {
  ok:          boolean;
  error?:      string;
  configPath?: string;
}

// ── Domain publishing ──────────────────────────────────────────────────────

/**
 * Writes an nginx reverse-proxy config for `hostname → 127.0.0.1:port`,
 * creates a sites-enabled symlink, tests the config, and reloads nginx.
 *
 * Port MUST have been fetched from the DB by the caller — never pass a
 * user-supplied port directly.
 *
 * Returns `{ ok: true, configPath }` on success or `{ ok: false, error }`.
 */
export async function publishDomain(
  hostname: string,
  port: number
): Promise<NginxPublishResult> {
  // ── Validate inputs ─────────────────────────────────────────────────────
  if (!isValidDomain(hostname)) {
    return { ok: false, error: `Invalid domain name: "${hostname}"` };
  }
  if (!Number.isInteger(port) || port < 4100 || port > 4999) {
    return {
      ok: false,
      error: `Port ${port} is outside the allowed range (4100–4999). Use the assigned deployment port.`,
    };
  }

  const configFilename = `${hostname}.conf`;
  const configPath     = path.join(NGINX_SITES_AVAILABLE, configFilename);
  const enabledPath    = path.join(NGINX_SITES_ENABLED,   configFilename);
  const configContent  = generateNginxConfig(hostname, port);

  // ── Ensure sites-available/prisom-projects exists ───────────────────────
  try {
    await fs.mkdir(NGINX_SITES_AVAILABLE, { recursive: true });
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM") {
      return {
        ok: false,
        error:
          `Permission denied: cannot create ${NGINX_SITES_AVAILABLE}. ` +
          `To fix, run on the VPS:\n` +
          `  sudo mkdir -p ${NGINX_SITES_AVAILABLE}\n` +
          `  sudo chown ${process.env.USER ?? "prisom"}:${process.env.USER ?? "prisom"} ${NGINX_SITES_AVAILABLE}`,
      };
    }
    return { ok: false, error: `Cannot create nginx directory: ${(e as Error).message}` };
  }

  // ── Write nginx config ──────────────────────────────────────────────────
  try {
    await fs.writeFile(configPath, configContent, { encoding: "utf8", flag: "w" });
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM") {
      return {
        ok: false,
        error:
          `Permission denied: cannot write ${configPath}. ` +
          `To fix, run on the VPS:\n` +
          `  sudo chown ${process.env.USER ?? "prisom"}:${process.env.USER ?? "prisom"} ${NGINX_SITES_AVAILABLE}`,
      };
    }
    return { ok: false, error: `Failed to write nginx config: ${(e as Error).message}` };
  }

  // ── Create/replace symlink in sites-enabled ─────────────────────────────
  try {
    // Remove stale symlink if it exists
    await fs.unlink(enabledPath).catch(() => {});
    await fs.symlink(configPath, enabledPath);
  } catch (e) {
    const code = (e as NodeJS.ErrnoException).code;
    if (code === "EACCES" || code === "EPERM") {
      return {
        ok: false,
        error:
          `Permission denied: cannot create symlink in ${NGINX_SITES_ENABLED}. ` +
          `To fix, run on the VPS:\n` +
          `  sudo chown ${process.env.USER ?? "prisom"}:${process.env.USER ?? "prisom"} ${NGINX_SITES_ENABLED}`,
      };
    }
    return {
      ok: false,
      error: `Failed to create nginx symlink: ${(e as Error).message}`,
    };
  }

  // ── Test nginx config ───────────────────────────────────────────────────
  try {
    await execFileAsync("nginx", ["-t"], { timeout: 10_000 });
  } catch (e) {
    // Config test failed — remove the broken symlink to avoid leaving nginx broken
    await fs.unlink(enabledPath).catch(() => {});
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return { ok: false, error: `nginx config test failed:\n${msg}` };
  }

  // ── Reload nginx ────────────────────────────────────────────────────────
  try {
    await execFileAsync("systemctl", ["reload", "nginx"], { timeout: 15_000 });
  } catch (e) {
    const stderr = (e as { stderr?: string }).stderr ?? "";
    const msg    = stderr.trim() || (e instanceof Error ? e.message : String(e));
    return {
      ok: false,
      error:
        `nginx config written and tested, but reload failed: ${msg}\n` +
        `You can reload manually with: sudo systemctl reload nginx`,
    };
  }

  return { ok: true, configPath };
}
