import type {
  DeployVerificationReport,
  DeployVerificationCheck,
} from "./deploy-verification-types";

const CATEGORY_LABELS: Record<DeployVerificationCheck["category"], string> = {
  commit:       "Commit Verification",
  panel_route:  "Panel Routes",
  project_route:"Project Routes",
  export:       "Export Verification",
  action:       "Action Gates",
  permissions:  "Permissions",
  safety:       "Safety",
  runtime:      "Runtime",
};

const CATEGORY_ORDER: DeployVerificationCheck["category"][] = [
  "commit", "panel_route", "project_route", "export", "action", "permissions", "safety", "runtime",
];

const STATUS_ICON: Record<DeployVerificationCheck["status"], string> = {
  pass:    "✅",
  warning: "⚠️",
  blocked: "🚫",
  manual:  "🔲",
  pending: "⏳",
};

export function exportDeployVerificationReport(report: DeployVerificationReport): string {
  const lines: string[] = [
    "# DEPLOY_VERIFICATION_REPORT.md",
    "",
    `**Project:** ${report.projectId}`,
    `**Generated:** ${new Date(report.generatedAt).toUTCString()}`,
    `**Status:** ${report.status.replace(/_/g, " ").toUpperCase()}`,
    "",
    "> Read-only — deploy verification documentation only. No production mutation.",
    "",
    "---",
    "",
    "## Context",
    "",
    "| Key | Value |",
    "| --- | --- |",
    "| Panel domain | projects.doorstepmanchester.uk |",
    "| Sardar domain | sardar-security-project.doorstepmanchester.uk |",
    "| PM2 process | prisom-projects |",
    "| Server path | /home/prisom/prisom-project-panel |",
    "| Sardar PM2 | project-sardar-security-project (DO NOT RESTART) |",
    "",
    "---",
    "",
    "## Commit Verification",
    "",
    `| Field | Value |`,
    `| --- | --- |`,
    `| Expected commit | ${report.expectedCommit || "_(not specified — run git rev-parse --short HEAD on server)_"} |`,
    `| Observed commit (last DB) | ${report.observedCommit || "_(not available — verify manually)_"} |`,
    "",
    "**Operator action:** SSH to server and run:",
    "```bash",
    "git -C /home/prisom/prisom-project-panel rev-parse --short HEAD",
    "git -C /home/prisom/prisom-project-panel log --oneline -8",
    "```",
    "",
    "---",
    "",
  ];

  if (report.blockers.length > 0) {
    lines.push("## ⛔ Blockers", "");
    for (const b of report.blockers) lines.push(`- ${b}`);
    lines.push("");
  }

  if (report.warnings.length > 0) {
    lines.push("## ⚠️ Warnings", "");
    for (const w of report.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  lines.push("---", "", "## Verification Checklist", "");

  for (const cat of CATEGORY_ORDER) {
    const catChecks = report.checks.filter((c) => c.category === cat);
    if (catChecks.length === 0) continue;
    lines.push(`### ${CATEGORY_LABELS[cat]}`, "");
    for (const c of catChecks) {
      const icon = STATUS_ICON[c.status];
      lines.push(`#### ${icon} ${c.label}`);
      lines.push("");
      lines.push(c.description);
      if (c.command) {
        lines.push("", "**Command:**", "```bash", c.command, "```");
      }
      if (c.evidence) lines.push("", `**Evidence:** ${c.evidence}`);
      if (c.nextStep) lines.push("", `**Next step:** ${c.nextStep}`);
      if (c.safetyNote) lines.push("", `> **Safety:** ${c.safetyNote}`);
      lines.push("");
    }
  }

  lines.push("---", "", "## Routes to Verify", "");
  for (const route of report.verifiedRoutes) lines.push(`- [ ] ${route}`);
  lines.push("");

  lines.push("---", "", "## Exports to Verify", "");
  for (const exp of report.exportsToVerify) lines.push(`- [ ] ${exp}`);
  lines.push("");

  lines.push("---", "", "## Action Gates to Verify", "");
  for (const act of report.actionsToVerify) lines.push(`- [ ] ${act}`);
  lines.push("");

  if (report.recommendedNextSteps.length > 0) {
    lines.push("---", "", "## Recommended Next Steps", "");
    for (const step of report.recommendedNextSteps) lines.push(`- ${step}`);
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "## Safety Notes",
    "",
    "- This report is read-only and generates no production changes.",
    "- All smoke checks must be run by an operator manually via curl or SSH.",
    "- Do not restart any PM2 process from the panel.",
    "- Do not touch Doorsteps/LocalShop (prisom-manager, prisom-backend).",
    "- Sardar production must remain live throughout verification.",
    "- No secrets are included in this report.",
    "",
    "---",
    "",
    "_Generated by Prisom Project Panel. Read-only — deploy verification only. No production mutation._",
    "",
  );

  return lines.join("\n");
}
