/**
 * lib/migration/portability-patch-planner.ts
 *
 * Sprint 25: Generates patch plans for known Replit portability blockers.
 *
 * Supported patches:
 *   1. APP_URL replacement — creates a getPublicBaseUrl() helper
 *   2. Email transport replacement — creates SMTP transport + patches email file
 *
 * All patches are deterministic and safe:
 *   - Only writes under the project source dir
 *   - Never overwrites .env or lock files (enforced by safety layer)
 *   - "before" content is captured at plan-time for conflict detection at apply-time
 *   - Diffs are generated for UI preview
 */

import path from "path";
import { promises as fs } from "fs";
import {
  checkProjectGitStatus,
  checkRecentBackup,
  validatePatchPath,
} from "./portability-patch-safety";
import type {
  PortabilityPatchPlan,
  PortabilityPatchFile,
  PatchSummary,
  PatchId,
} from "./portability-patch-types";
import { PATCH_IDS } from "./portability-patch-types";

// ── Diff generator ────────────────────────────────────────────────────────────

/**
 * Generate a simple unified-style diff for display purposes.
 * For CREATE operations (no `before`), all lines are shown as added.
 * For UPDATE operations, changed lines are shown with +/- prefix.
 */
export function generateSimpleDiff(
  filename: string,
  before:   string | undefined,
  after:    string,
): string {
  if (!before) {
    // New file — all lines added
    const lines   = after.split("\n");
    const header  = `--- /dev/null\n+++ b/${filename}\n@@ -0,0 +1,${lines.length} @@`;
    const body    = lines.map((l) => `+${l}`).join("\n");
    return `${header}\n${body}`;
  }
  if (before === after) return "(no changes)";

  const beforeLines = before.split("\n");
  const afterLines  = after.split("\n");
  const result: string[] = [`--- a/${filename}`, `+++ b/${filename}`];

  // Simple sequential diff (works correctly for targeted/surgical replacements)
  const max = Math.max(beforeLines.length, afterLines.length);
  for (let i = 0; i < max; i++) {
    const b = i < beforeLines.length ? beforeLines[i] : undefined;
    const a = i < afterLines.length  ? afterLines[i]  : undefined;
    if (b === a)          result.push(` ${b ?? ""}`);
    else if (a === undefined) result.push(`-${b ?? ""}`);
    else if (b === undefined) result.push(`+${a}`);
    else { result.push(`-${b}`); result.push(`+${a}`); }
  }
  return result.join("\n");
}

// ── Public-URL helper content ─────────────────────────────────────────────────

function generatePublicUrlHelper(): string {
  return `/**
 * getPublicBaseUrl — portable public URL helper.
 *
 * Generated by Prisom Migration Assistant.
 *
 * Priority order:
 *   1. APP_URL / PUBLIC_BASE_URL environment variable (set in Secrets Vault)
 *   2. x-forwarded-proto + x-forwarded-host headers (nginx proxy headers)
 *   3. host header
 *   4. REPLIT_DOMAINS fallback (keeps Replit compatibility during transition)
 *   5. localhost fallback for local dev
 *
 * Usage:
 *   import { getPublicBaseUrl } from "./lib/public-url";
 *   const baseUrl = getPublicBaseUrl(req);  // or getPublicBaseUrl() if no req
 */

export function getPublicBaseUrl(
  req?: { headers?: Record<string, string | string[] | undefined> },
): string {
  // 1. Explicit env var (set APP_URL in Secrets Vault for production)
  const explicit = process.env.APP_URL || process.env.PUBLIC_BASE_URL;
  if (explicit) return explicit.replace(/\\/$/, "");

  // 2. Nginx / reverse-proxy forwarded headers
  const forwardedProto = getHeader(req, "x-forwarded-proto");
  const forwardedHost  = getHeader(req, "x-forwarded-host");
  if (forwardedHost) {
    const proto = forwardedProto || "https";
    return \`\${proto}://\${forwardedHost}\`.replace(/\\/$/, "");
  }

  // 3. Host header
  const host = getHeader(req, "host");
  if (host) return \`https://\${host}\`.replace(/\\/$/, "");

  // 4. Replit fallback (keeps existing Replit deployment working)
  const replitDomains = process.env.REPLIT_DOMAINS;
  if (replitDomains) {
    const first = replitDomains.split(",")[0]?.trim();
    if (first) return \`https://\${first}\`.replace(/\\/$/, "");
  }

  // 5. Local dev fallback
  const port = process.env.PORT || "3000";
  return \`http://localhost:\${port}\`;
}

function getHeader(
  req: { headers?: Record<string, string | string[] | undefined> } | undefined,
  name: string,
): string | undefined {
  const value = req?.headers?.[name] ?? req?.headers?.[name.toLowerCase()];
  if (Array.isArray(value)) return value[0];
  return typeof value === "string" ? value : undefined;
}
`;
}

// ── SMTP transport content ────────────────────────────────────────────────────

function generateSmtpTransportContent(): string {
  return `/**
 * email-transport-smtp.ts — portable SMTP mail transport.
 *
 * Generated by Prisom Migration Assistant.
 *
 * Replaces Replit google-mail connector with SMTP (nodemailer).
 * Configure these secrets in the Secrets Vault:
 *   SMTP_HOST   — e.g. smtp.resend.com or smtp.sendgrid.net
 *   SMTP_PORT   — typically 587 (TLS) or 465 (SSL)
 *   SMTP_SECURE — "true" for port 465, leave unset/false for 587
 *   SMTP_USER   — your SMTP username or API key
 *   SMTP_PASS   — your SMTP password or API key
 *   SMTP_FROM   — sender address, e.g. hello@yourdomain.com
 */

import nodemailer from "nodemailer";
import type { Transporter } from "nodemailer";

let _transporter: Transporter | null = null;

/**
 * Returns a cached nodemailer SMTP transporter.
 * Throws a clear config error if SMTP_HOST is not set.
 */
export function getMailTransporter(): Transporter {
  if (_transporter) return _transporter;

  const smtpHost = process.env.SMTP_HOST;
  if (!smtpHost) {
    throw new Error(
      "[email] SMTP is not configured. " +
        "Add SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, and SMTP_FROM " +
        "to the Secrets Vault before deploying.",
    );
  }

  _transporter = nodemailer.createTransport({
    host:   smtpHost,
    port:   Number(process.env.SMTP_PORT ?? 587),
    secure: process.env.SMTP_SECURE === "true",
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });

  return _transporter;
}

/** Default sender address. Falls back to SMTP_USER if SMTP_FROM is not set. */
export function getDefaultFrom(): string {
  return process.env.SMTP_FROM ?? process.env.SMTP_USER ?? "noreply@localhost";
}
`;
}

// ── Helper: safe file read ────────────────────────────────────────────────────

async function readFileSafe(absPath: string, maxBytes = 200 * 1024): Promise<string | null> {
  try {
    const stat = await fs.lstat(absPath);
    if (!stat.isFile() || stat.isSymbolicLink()) return null;
    if (stat.size > maxBytes) return null;
    return await fs.readFile(absPath, "utf8");
  } catch {
    return null;
  }
}

// ── APP_URL patch planner ─────────────────────────────────────────────────────

async function planAppUrlPatch(
  projectId:  string,
  sourceDir:  string,
  allContent: string,
  fileList:   string[],
): Promise<PortabilityPatchPlan> {
  const usesReplitDomains = allContent.includes("REPLIT_DOMAINS");

  if (!usesReplitDomains) {
    return basePlan(PATCH_IDS.APP_URL, projectId, "not_applicable", sourceDir, "REPLIT_DOMAINS is not used in this project.", [], []);
  }

  // Determine helper file location based on project structure
  let helperRelPath = "src/lib/public-url.ts";
  if (fileList.some((f) => f.startsWith("artifacts/") && f.endsWith("src/lib/"))) {
    // Monorepo with artifacts — find api server path
    const apiSrcLib = fileList.find((f) => f.includes("/src/lib/") && f.includes("api"));
    if (apiSrcLib) {
      helperRelPath = path.dirname(apiSrcLib).replace(/\\/g, "/") + "/public-url.ts";
    } else {
      const firstSrcLib = fileList.find((f) => /src\/lib\//.test(f));
      if (firstSrcLib) {
        helperRelPath = path.dirname(firstSrcLib).replace(/\\/g, "/") + "/public-url.ts";
      }
    }
  } else {
    const firstSrcLib = fileList.find((f) => /src\/lib\//.test(f));
    if (firstSrcLib) {
      helperRelPath = path.dirname(firstSrcLib).replace(/\\/g, "/") + "/public-url.ts";
    }
  }

  // Check if already applied
  const helperAbs = path.join(sourceDir, helperRelPath);
  const existingHelper = await readFileSafe(helperAbs);
  if (existingHelper && existingHelper.includes("getPublicBaseUrl")) {
    return basePlan(PATCH_IDS.APP_URL, projectId, "already_applied", sourceDir,
      `${helperRelPath} already contains getPublicBaseUrl().`, [], []);
  }

  // Validate the path
  const pathCheck = validatePatchPath(helperRelPath, sourceDir);
  if (!pathCheck.ok) {
    return basePlan(PATCH_IDS.APP_URL, projectId, "blocked", sourceDir, pathCheck.error, [], []);
  }

  const helperContent = generatePublicUrlHelper();
  const patchFile: PortabilityPatchFile = {
    path:      helperRelPath,
    operation: "create",
    after:     helperContent,
    diff:      generateSimpleDiff(helperRelPath, undefined, helperContent),
  };

  // Find files using REPLIT_DOMAINS for the manualSteps list
  const filesUsingDomains = fileList.filter((f) => {
    if (f.includes("node_modules")) return false;
    return f.endsWith(".ts") || f.endsWith(".tsx") || f.endsWith(".js") || f.endsWith(".jsx");
  }).slice(0, 10);  // list only, not auto-patched

  const manualSteps = [
    `Import the helper in files that use REPLIT_DOMAINS:`,
    `  import { getPublicBaseUrl } from "${helperRelPath.replace(".ts", "")}";`,
    `Replace process.env.REPLIT_DOMAINS usages with: getPublicBaseUrl(req)`,
    `Files most likely to need updates:`,
    ...filesUsingDomains.map((f) => `  • ${f}`),
    `Then add APP_URL to the Secrets Vault (production environment).`,
  ];

  const [gitStatus, hasRecentBackup] = await Promise.all([
    checkProjectGitStatus(sourceDir),
    checkRecentBackup(projectId),
  ]);

  return {
    id:              PATCH_IDS.APP_URL,
    projectId,
    title:           "APP_URL replacement",
    description:     "Creates a getPublicBaseUrl() helper that reads APP_URL from the Secrets Vault. Keeps REPLIT_DOMAINS as a fallback for Replit compatibility.",
    severity:        "required",
    status:          "available",
    files:           [patchFile],
    requiredSecrets: ["APP_URL"],
    requiredPackages: [],
    warnings:        [
      "Files using REPLIT_DOMAINS must be manually updated to call getPublicBaseUrl(req) — see manual steps.",
      "Do not remove REPLIT_DOMAINS entirely — the helper keeps it as a fallback.",
    ],
    manualSteps,
    gitStatus,
    hasRecentBackup,
    createdAt: new Date().toISOString(),
  };
}

// ── Email transport patch planner ─────────────────────────────────────────────

async function planEmailTransportPatch(
  projectId:  string,
  sourceDir:  string,
  allContent: string,
  fileList:   string[],
  allDeps:    Record<string, string>,
): Promise<PortabilityPatchPlan> {
  const hasReplitConnector =
    !!allDeps["@replit/connectors-sdk"] ||
    allContent.includes("@replit/connectors-sdk") ||
    allContent.includes("getGoogleMailTransporter");

  if (!hasReplitConnector) {
    return basePlan(PATCH_IDS.EMAIL_TRANSPORT, projectId, "not_applicable", sourceDir,
      "Replit google-mail connector not detected.", [], []);
  }

  const hasNodemailer = !!allDeps["nodemailer"];
  const requiredPackages = hasNodemailer ? [] : ["nodemailer"];

  // Find the email utility file
  const emailFiles = fileList.filter((f) =>
    !f.includes("node_modules") &&
    /email/i.test(path.basename(f)) &&
    (f.endsWith(".ts") || f.endsWith(".js")) &&
    !f.endsWith(".spec.ts") && !f.endsWith(".test.ts"),
  );

  // Among them, pick the one containing the Replit connector import
  let targetEmailFile: string | null = null;
  let targetEmailContent: string | null = null;

  for (const ef of emailFiles) {
    const pathCheck = validatePatchPath(ef, sourceDir);
    if (!pathCheck.ok) continue;
    const content = await readFileSafe(pathCheck.absPath);
    if (content && (content.includes("@replit/connectors-sdk") || content.includes("getGoogleMailTransporter"))) {
      targetEmailFile    = ef;
      targetEmailContent = content;
      break;
    }
  }

  // Determine transport file location
  let transportRelPath = "src/lib/email-transport-smtp.ts";
  if (targetEmailFile) {
    const dir = path.dirname(targetEmailFile).replace(/\\/g, "/");
    transportRelPath = `${dir}/email-transport-smtp.ts`;
  }

  // Check if already applied
  const transportAbs = path.join(sourceDir, transportRelPath);
  const existingTransport = await readFileSafe(transportAbs);
  if (existingTransport && existingTransport.includes("getMailTransporter")) {
    return basePlan(PATCH_IDS.EMAIL_TRANSPORT, projectId, "already_applied", sourceDir,
      `${transportRelPath} already contains SMTP transport.`, [], []);
  }

  const pathCheck = validatePatchPath(transportRelPath, sourceDir);
  if (!pathCheck.ok) {
    return basePlan(PATCH_IDS.EMAIL_TRANSPORT, projectId, "blocked", sourceDir, pathCheck.error, [], []);
  }

  const files: PortabilityPatchFile[] = [];

  // File 1: CREATE the SMTP transport
  const transportContent = generateSmtpTransportContent();
  files.push({
    path:      transportRelPath,
    operation: "create",
    after:     transportContent,
    diff:      generateSimpleDiff(transportRelPath, undefined, transportContent),
  });

  // File 2: UPDATE the email file if found — surgical import + call replacement
  if (targetEmailFile && targetEmailContent) {
    const emailPathCheck = validatePatchPath(targetEmailFile, sourceDir);
    if (emailPathCheck.ok) {
      const patched = patchEmailFileContent(targetEmailContent, transportRelPath);
      if (patched !== targetEmailContent) {
        files.push({
          path:      targetEmailFile,
          operation: "update",
          before:    targetEmailContent,
          after:     patched,
          diff:      generateSimpleDiff(targetEmailFile, targetEmailContent, patched),
        });
      }
    }
  }

  const relImportPath = targetEmailFile
    ? path.relative(path.dirname(targetEmailFile), transportRelPath).replace(/\\/g, "/").replace(/\.ts$/, "")
    : "./email-transport-smtp";

  const manualSteps: string[] = [];
  if (!targetEmailFile) {
    manualSteps.push(
      `Could not automatically locate the email utility file with the Replit connector.`,
      `Manually update your email transport to import getMailTransporter from "${relImportPath}".`,
      `Replace: const transporter = await getGoogleMailTransporter();`,
      `With:    const transporter = getMailTransporter();`,
    );
  } else if (files.length === 1) {
    // Transport file created but email file not patched (patched === original)
    manualSteps.push(
      `In ${targetEmailFile}: replace the @replit/connectors-sdk import with:`,
      `  import { getMailTransporter } from "${relImportPath}";`,
      `Replace: const transporter = await getGoogleMailTransporter();`,
      `With:    const transporter = getMailTransporter();`,
    );
  }

  if (requiredPackages.length > 0) {
    manualSteps.push(`Install missing package: ${requiredPackages.join(", ")}`);
    manualSteps.push(`After applying, run your install command in the terminal.`);
  }

  const [gitStatus, hasRecentBackup] = await Promise.all([
    checkProjectGitStatus(sourceDir),
    checkRecentBackup(projectId),
  ]);

  return {
    id:              PATCH_IDS.EMAIL_TRANSPORT,
    projectId,
    title:           "Email transport replacement",
    description:     "Creates an SMTP email transport (nodemailer) to replace the Replit google-mail connector. Preserves existing email function signatures.",
    severity:        "required",
    status:          "available",
    files,
    requiredSecrets: ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS", "SMTP_FROM"],
    requiredPackages,
    warnings: [
      "After applying, add SMTP credentials to the Secrets Vault before deploying.",
      requiredPackages.length > 0
        ? `nodemailer must be installed. Run the install command shown after apply.`
        : "nodemailer is already in your dependencies.",
    ].filter(Boolean),
    manualSteps,
    gitStatus,
    hasRecentBackup,
    createdAt: new Date().toISOString(),
  };
}

// ── Email file surgical patcher ───────────────────────────────────────────────

function patchEmailFileContent(content: string, transportRelPath: string): string {
  let patched = content;

  // Compute relative import path for the transport file
  const transportImportPath = "./" + path.basename(transportRelPath).replace(/\.ts$/, "");

  // 1. Replace @replit/connectors-sdk import line(s)
  patched = patched.replace(
    /^import\s*\{[^}]*getGoogleMailTransporter[^}]*\}\s*from\s*["']@replit\/connectors-sdk["'];?\r?\n?/gm,
    `import nodemailer from "nodemailer";\nimport { getMailTransporter } from "${transportImportPath}";\n`,
  );

  // 2. Replace "const X = await getGoogleMailTransporter()" calls
  patched = patched.replace(
    /(?:const|let)\s+(\w+)\s*=\s*await\s+getGoogleMailTransporter\(\)\s*;?/g,
    (_, varName) => `const ${varName} = getMailTransporter();`,
  );

  // 3. Remove any standalone "await getGoogleMailTransporter();" lines
  patched = patched.replace(
    /^\s*await\s+getGoogleMailTransporter\(\)\s*;?\r?\n?/gm,
    "",
  );

  return patched;
}

// ── Base plan builder (for not_applicable / blocked / already_applied) ────────

async function basePlan(
  id:           PatchId,
  projectId:    string,
  status:       PortabilityPatchPlan["status"],
  sourceDir:    string,
  statusReason: string,
  requiredSecrets: string[],
  requiredPackages: string[],
): Promise<PortabilityPatchPlan> {
  const [gitStatus, hasRecentBackup] = await Promise.all([
    checkProjectGitStatus(sourceDir),
    checkRecentBackup(projectId),
  ]);
  const titles: Record<PatchId, string> = {
    [PATCH_IDS.APP_URL]:         "APP_URL replacement",
    [PATCH_IDS.EMAIL_TRANSPORT]: "Email transport replacement",
  };
  const descs: Record<PatchId, string> = {
    [PATCH_IDS.APP_URL]:         "Creates a getPublicBaseUrl() helper that uses APP_URL from the Secrets Vault.",
    [PATCH_IDS.EMAIL_TRANSPORT]: "Creates an SMTP email transport to replace the Replit google-mail connector.",
  };
  return {
    id, projectId,
    title:           titles[id],
    description:     descs[id],
    severity:        "required",
    status,
    statusReason,
    files:           [],
    requiredSecrets,
    requiredPackages,
    warnings:        [],
    manualSteps:     [],
    gitStatus,
    hasRecentBackup,
    createdAt:       new Date().toISOString(),
  };
}

// ── Main entry points ─────────────────────────────────────────────────────────

export type PlannerInput = {
  projectId: string;
  sourceDir: string;
  allContent: string;
  fileList:   string[];
  allDeps:    Record<string, string>;
};

export async function planPatch(
  patchId: PatchId,
  input:   PlannerInput,
): Promise<PortabilityPatchPlan> {
  const { projectId, sourceDir, allContent, fileList, allDeps } = input;
  switch (patchId) {
    case PATCH_IDS.APP_URL:
      return planAppUrlPatch(projectId, sourceDir, allContent, fileList);
    case PATCH_IDS.EMAIL_TRANSPORT:
      return planEmailTransportPatch(projectId, sourceDir, allContent, fileList, allDeps);
    default:
      return basePlan(patchId, projectId, "blocked", sourceDir, "Unknown patch ID.", [], []);
  }
}

export async function listPatchSummaries(
  input: PlannerInput,
): Promise<PatchSummary[]> {
  const plans = await Promise.all([
    planPatch(PATCH_IDS.APP_URL,         input),
    planPatch(PATCH_IDS.EMAIL_TRANSPORT, input),
  ]);
  return plans.map((p) => ({
    id:                 p.id,
    title:              p.title,
    description:        p.description,
    severity:           p.severity,
    status:             p.status,
    statusReason:       p.statusReason,
    affectedFilesCount: p.files.length,
    requiredSecrets:    p.requiredSecrets,
    requiredPackages:   p.requiredPackages,
  }));
}
