/**
 * lib/operator-training/operator-training-export.ts
 *
 * Sprint 74: Generates OPERATOR_TRAINING_PACK.md.
 * No secrets. No production mutation.
 */

import type { OperatorTrainingPack, TrainingAudience } from "./operator-training-types";

const AUDIENCE_LABEL: Record<TrainingAudience, string> = {
  admin:     "Admin",
  operator:  "Operator",
  developer: "Developer",
  client:    "Client",
};

export function exportOperatorTrainingPack(pack: OperatorTrainingPack): string {
  const generatedAt = new Date(pack.generatedAt).toUTCString();
  const sections: string[] = [];

  sections.push(`# Operator Training Pack — Project ${pack.projectId}

> Generated: ${generatedAt}
> This document is read-only. No production mutation. No secrets included.

## About This Document

This training pack is for operators, admins, and developers responsible for running this project after launch. It covers daily operations, health checks, log reading, QA workflows, emergency rollback, and escalation rules.
`);

  // Sections
  sections.push("## Training Sections\n");
  for (const s of pack.sections) {
    sections.push(`### ${s.title} *(audience: ${AUDIENCE_LABEL[s.audience]})*\n`);
    sections.push(`${s.summary}\n`);
    sections.push(`**Steps:**\n${s.steps.map((step) => `- ${step}`).join("\n")}\n`);
    if (s.safetyNotes.length > 0) {
      sections.push(`**Safety Notes:**\n${s.safetyNotes.map((n) => `- ⚠️ ${n}`).join("\n")}\n`);
    }
  }

  // Daily checklist
  sections.push(`## Daily Operator Checklist

Complete every morning before starting work:

${pack.dailyChecklist.map((item) => `- [ ] ${item}`).join("\n")}
`);

  // Weekly checklist
  sections.push(`## Weekly Checklist

${pack.weeklyChecklist.map((item) => `- [ ] ${item}`).join("\n")}
`);

  // Launch day
  sections.push(`## Launch-Day Checklist

Do not proceed to production cutover until all items are checked:

${pack.launchDayChecklist.map((item) => `- [ ] ${item}`).join("\n")}
`);

  // Emergency
  sections.push(`## Emergency Rollback Checklist

Follow this sequence if production breaks after cutover:

${pack.emergencyChecklist.map((item) => `- [ ] ${item}`).join("\n")}
`);

  // Escalation
  sections.push(`## Escalation Rules

${pack.escalationRules.map((rule) => `- ${rule}`).join("\n")}
`);

  // Pages to use
  if (pack.pagesToUse.length > 0) {
    sections.push(`## Pages to Use

| Page | Path | Notes |
|------|------|-------|
${pack.pagesToUse.map((p) => `| ${p.label} | \`${p.path}\` | ${p.note} |`).join("\n")}
`);
  }

  // Pages to avoid
  if (pack.pagesToAvoid.length > 0) {
    sections.push(`## Actions to Avoid from the Panel

| Action | Reason |
|--------|--------|
${pack.pagesToAvoid.map((p) => `| ${p.label} | ${p.note} |`).join("\n")}
`);
  }

  sections.push(`---
*Generated by Prisom Project Panel — Sprint 74. This document is read-only and contains no secrets.*
`);

  return sections.join("\n");
}
