/**
 * lib/project-templates/client-migration-export.ts
 *
 * Sprint 72: Generates CLIENT_MIGRATION_PLAN.md from a template migration plan.
 * No secret values — only key names, categories, and structural guidance.
 */

import type { TemplateMigrationPlan } from "./project-template-types";

function table(headers: string[], rows: string[][]): string {
  const sep  = headers.map((h) => "-".repeat(Math.max(h.length, 3)));
  const head = `| ${headers.join(" | ")} |`;
  const div  = `| ${sep.join(" | ")} |`;
  const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
  return [head, div, body].join("\n");
}

export function exportClientMigrationPlan(plan: TemplateMigrationPlan): string {
  const { template, generatedAt, steps, blockers, warnings, nextSteps } = plan;
  const lines: string[] = [];

  lines.push(`# CLIENT_MIGRATION_PLAN.md`);
  lines.push(``);
  lines.push(`> Template: **${template.label}** — Generated: ${new Date(generatedAt).toUTCString()}`);
  lines.push(``);
  lines.push(`**Description:** ${template.description}`);
  lines.push(``);

  // Best for
  lines.push(`## Best For`);
  lines.push(``);
  for (const b of template.bestFor) {
    lines.push(`- ${b}`);
  }
  lines.push(``);

  // Blockers
  if (blockers.length > 0) {
    lines.push(`## Blockers`);
    lines.push(``);
    for (const b of blockers) {
      lines.push(`- 🔴 ${b}`);
    }
    lines.push(``);
  }

  // Warnings
  if (warnings.length > 0) {
    lines.push(`## Warnings`);
    lines.push(``);
    for (const w of warnings) {
      lines.push(`- ⚠️ ${w}`);
    }
    lines.push(``);
  }

  // Expected services
  lines.push(`## Expected Services`);
  lines.push(``);
  if (template.expectedServices.length === 0) {
    lines.push(`_No services pre-configured — customize for your project._`);
  } else {
    lines.push(table(
      ["Service", "Kind", "Build Hint", "Start / Output Hint", "Health Path", "Route"],
      template.expectedServices.map((s) => [
        s.name,
        s.kind,
        s.buildCommandHint   ?? "—",
        s.startCommandHint   ?? s.outputPathHint ?? "—",
        s.healthPathHint     ?? "—",
        s.routeHint          ?? "—",
      ]),
    ));
  }
  lines.push(``);

  // Expected env categories (names only, no values)
  lines.push(`## Expected Environment Variables`);
  lines.push(``);
  lines.push(`> Values are never included — configure these in the Settings → Environment section.`);
  lines.push(``);
  if (template.expectedEnv.length === 0) {
    lines.push(`_No env vars pre-configured._`);
  } else {
    const categories = [...new Set(template.expectedEnv.map((e) => e.category))].sort();
    for (const cat of categories) {
      const entries = template.expectedEnv.filter((e) => e.category === cat);
      lines.push(`### ${cat.charAt(0).toUpperCase() + cat.slice(1)}`);
      lines.push(``);
      lines.push(table(
        ["Key Name", "Required", "Secret", "Description"],
        entries.map((e) => [
          `\`${e.name}\``,
          e.required ? "Yes" : "No",
          e.secret   ? "Yes" : "No",
          e.description || "—",
        ]),
      ));
      lines.push(``);
    }
  }

  // Onboarding checklist
  lines.push(`## Onboarding Checklist`);
  lines.push(``);
  lines.push(table(
    ["#", "Task", "Required", "Description", "Done"],
    template.onboardingChecklist.map((item, i) => [
      String(i + 1),
      item.label,
      item.required ? "Yes" : "No",
      item.description,
      "☐",
    ]),
  ));
  lines.push(``);

  // First-run migration steps
  lines.push(`## First-Run Migration Sequence`);
  lines.push(``);
  const statusIcon = (s: string) => {
    if (s === "pass")    return "✅";
    if (s === "warning") return "⚠️";
    if (s === "manual")  return "🔧";
    return "⏳";
  };
  for (const step of steps) {
    lines.push(`### ${statusIcon(step.status)} ${step.label}`);
    lines.push(``);
    lines.push(step.message);
    if (step.linkHref) {
      lines.push(``);
      lines.push(`**Page:** \`${step.linkHref}\``);
    }
    lines.push(``);
  }

  // Recommended pages
  lines.push(`## Recommended Pages`);
  lines.push(``);
  lines.push(table(
    ["Page", "Path Suffix", "Why"],
    template.recommendedPages.map((p) => [p.label, p.hrefSuffix, p.reason]),
  ));
  lines.push(``);

  // Next steps
  if (nextSteps.length > 0) {
    lines.push(`## Next Steps`);
    lines.push(``);
    nextSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push(``);
  }

  // Safety notes
  if (template.safetyNotes.length > 0) {
    lines.push(`## Safety Notes`);
    lines.push(``);
    for (const note of template.safetyNotes) {
      lines.push(`- ⚠️ ${note}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`_Generated by Prisom Project Panel — Sprint 72 Client Migration Templates_`);

  return lines.join("\n");
}
