import { generateProjectKnowledgeBase } from "./project-knowledge-builder";
import type { ProjectHelpCenterReport } from "./help-center-types";

// ── Shared helpers ────────────────────────────────────────────────────────────

function safetyHeader(): string {
  return [
    "> **Safety**: This export contains no secret values.",
    "> Only file names, function names, route paths, and variable names (not values) are included.",
    "> Generated by Prisom Project Panel — read-only documentation only.",
    "> No production mutation, no DNS changes, no PM2 restarts, no migrations triggered by this export.",
  ].join("\n");
}

function excludedPathsSummary(paths: string[]): string {
  if (paths.length === 0) return "";
  const shown = paths.slice(0, 15);
  return [
    "## Excluded Paths",
    "",
    "The following paths were excluded from scanning:",
    "",
    shown.map((p) => `- \`${p}\``).join("\n"),
    paths.length > 15 ? `- … and ${paths.length - 15} more` : "",
    "",
    "Hard exclusions: .env, node_modules, .git, .next, dist, build, coverage, storage/backups, *.pem, *.key, *.crt, *.log",
  ]
    .filter((l) => l !== "")
    .join("\n");
}

// ── PROJECT_KNOWLEDGE_BASE.md ─────────────────────────────────────────────────

export async function exportProjectKnowledgeBase(input: {
  projectId: string;
}): Promise<{ filename: string; markdown: string }> {
  const report = await generateProjectKnowledgeBase(input);

  const lines: string[] = [
    "# PROJECT_KNOWLEDGE_BASE.md",
    "",
    `**Generated:** ${new Date(report.generatedAt).toUTCString()}`,
    `**Files scanned:** ${report.fileCount}`,
    `**Frameworks:** ${report.frameworks.join(", ") || "Next.js, React, Prisma, Tailwind CSS"}`,
    "",
    safetyHeader(),
    "",
    "---",
    "",
  ];

  for (const section of report.sections) {
    lines.push(section.content);
    lines.push("");
    lines.push("---");
    lines.push("");
  }

  lines.push(excludedPathsSummary(report.excludedPaths));

  if (report.warnings.length > 0) {
    lines.push("", "## Scan Warnings", "");
    for (const w of report.warnings) lines.push(`- ${w}`);
  }

  lines.push("", "---", "", "*End of PROJECT_KNOWLEDGE_BASE.md*");

  return { filename: "PROJECT_KNOWLEDGE_BASE.md", markdown: lines.join("\n") };
}

// ── PROJECT_FILE_INVENTORY.md ─────────────────────────────────────────────────

export async function exportProjectFileInventory(input: {
  projectId: string;
}): Promise<{ filename: string; markdown: string }> {
  const report = await generateProjectKnowledgeBase(input);

  const lines: string[] = [
    "# PROJECT_FILE_INVENTORY.md",
    "",
    `**Generated:** ${new Date(report.generatedAt).toUTCString()}`,
    `**Total files:** ${report.fileCount}`,
    "",
    safetyHeader(),
    "",
    "---",
    "",
    "## Language Distribution",
    "",
    "| Language | Count |",
    "| --- | --- |",
    ...Object.entries(report.languages)
      .sort(([, a], [, b]) => b - a)
      .map(([lang, count]) => `| ${lang} | ${count} |`),
    "",
    "---",
    "",
    "## File Inventory",
    "",
  ];

  // Group by category
  const categories = [
    "page", "server_action", "component", "library",
    "schema", "config", "script", "export", "style", "test", "unknown",
  ] as const;

  for (const cat of categories) {
    const items = report.inventory.filter((i) => i.category === cat);
    if (items.length === 0) continue;

    const catLabel = cat.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
    lines.push(`### ${catLabel} (${items.length})`);
    lines.push("");
    lines.push("| File | Language | Size | Summary |");
    lines.push("| --- | --- | --- | --- |");

    for (const item of items) {
      const size    = item.sizeBytes ? `${Math.round(item.sizeBytes / 1024)}KB` : "—";
      const summary = item.summary.replace(/\|/g, "–").slice(0, 80);
      lines.push(`| \`${item.path}\` | ${item.language} | ${size} | ${summary} |`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(excludedPathsSummary(report.excludedPaths));

  if (report.warnings.length > 0) {
    lines.push("", "## Scan Warnings", "");
    for (const w of report.warnings) lines.push(`- ${w}`);
  }

  lines.push("", "---", "", "*End of PROJECT_FILE_INVENTORY.md*");

  return { filename: "PROJECT_FILE_INVENTORY.md", markdown: lines.join("\n") };
}

// ── PROJECT_METHODS_AND_RESOURCES.md ─────────────────────────────────────────

export async function exportProjectMethodsAndResources(input: {
  projectId: string;
}): Promise<{ filename: string; markdown: string }> {
  const report = await generateProjectKnowledgeBase(input);

  const methods = collectMethods(report);
  const lines: string[] = [
    "# PROJECT_METHODS_AND_RESOURCES.md",
    "",
    `**Generated:** ${new Date(report.generatedAt).toUTCString()}`,
    `**Files scanned:** ${report.fileCount}`,
    "",
    safetyHeader(),
    "",
    "---",
    "",
    "## Frameworks and Libraries",
    "",
    ...report.frameworks.map((f) => `- ${f}`),
    "",
    "## Resources Used",
    "",
    ...report.resources.map((r) => `- ${r}`),
    "",
    "---",
    "",
    "## Server Action Methods",
    "",
    "| Action | File |",
    "| --- | --- |",
    ...methods.actions.map(({ name, file }) => `| \`${name}\` | \`${file}\` |`),
    "",
    "---",
    "",
    "## Exported Functions",
    "",
    "| Function | File | Category |",
    "| --- | --- | --- |",
    ...methods.exports.slice(0, 100).map(({ name, file, category }) => `| \`${name}\` | \`${file}\` | ${category} |`),
    "",
    "---",
    "",
    "## Routes",
    "",
    "| Route | File |",
    "| --- | --- |",
    ...methods.routes.map(({ route, file }) => `| \`${route}\` | \`${file}\` |`),
    "",
    "---",
    "",
    "## External Package Imports",
    "",
    "| Package | Used in files |",
    "| --- | --- |",
    ...methods.packages.slice(0, 30).map(({ pkg, count }) => `| \`${pkg}\` | ${count} file${count > 1 ? "s" : ""} |`),
    "",
    "---",
    "",
    excludedPathsSummary(report.excludedPaths),
    "",
    "---",
    "",
    "*End of PROJECT_METHODS_AND_RESOURCES.md*",
  ];

  return { filename: "PROJECT_METHODS_AND_RESOURCES.md", markdown: lines.join("\n") };
}

// ── Method extractor ──────────────────────────────────────────────────────────

function collectMethods(report: ProjectHelpCenterReport) {
  const actions: Array<{ name: string; file: string }> = [];
  const exports: Array<{ name: string; file: string; category: string }> = [];
  const routes:  Array<{ route: string; file: string }> = [];
  const pkgCounts: Record<string, number> = {};

  for (const item of report.inventory) {
    for (const action of item.actions ?? []) {
      actions.push({ name: action, file: item.path });
    }
    for (const exp of item.importantExports) {
      exports.push({ name: exp, file: item.path, category: item.category });
    }
    for (const route of item.routes ?? []) {
      routes.push({ route, file: item.path });
    }
    for (const imp of item.importantImports) {
      pkgCounts[imp] = (pkgCounts[imp] ?? 0) + 1;
    }
  }

  const packages = Object.entries(pkgCounts)
    .sort(([, a], [, b]) => b - a)
    .map(([pkg, count]) => ({ pkg, count }));

  return { actions, exports, routes, packages };
}
