/**
 * lib/project-profiles/project-profile-export.ts
 *
 * Sprint 71: Generates PROJECT_PROFILE_REPORT.md from a detected migration profile.
 * No secret values included — only key names, categories, and structural metadata.
 */

import type { ProjectMigrationProfile } from "./project-profile-types";
import {
  getProjectDisplayName,
  getProjectProfileBadge,
  getDefaultStagingDomain,
  getDefaultProductionDomain,
} from "./profile-labels";

function table(headers: string[], rows: string[][]): string {
  const sep  = headers.map((h) => "-".repeat(Math.max(h.length, 3)));
  const head = `| ${headers.join(" | ")} |`;
  const div  = `| ${sep.join(" | ")} |`;
  const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
  return [head, div, body].join("\n");
}

export function exportProjectProfileReport(profile: ProjectMigrationProfile): string {
  const lines: string[] = [];
  const generatedAt = new Date().toUTCString();

  lines.push(`# PROJECT_PROFILE_REPORT.md`);
  lines.push(``);
  lines.push(`> Generated: ${generatedAt}`);
  lines.push(``);

  // ── Summary ──────────────────────────────────────────────────────────────────

  lines.push(`## Project Profile Summary`);
  lines.push(``);
  lines.push(table(
    ["Field", "Value"],
    [
      ["Display Name",      getProjectDisplayName(profile)],
      ["Profile Kind",      getProjectProfileBadge(profile)],
      ["Ecommerce",         profile.isEcommerce ? "Yes" : "No"],
      ["Sardar Project",    profile.isSardar ? "Yes" : "No"],
      ["Slug",              profile.slug ?? "—"],
      ["Production Domain", getDefaultProductionDomain(profile) || "—"],
      ["Staging Domain",    getDefaultStagingDomain(profile) || "—"],
    ],
  ));
  lines.push(``);
  lines.push(`**Description:** ${profile.description}`);
  lines.push(``);

  // ── Expected Services ────────────────────────────────────────────────────────

  lines.push(`## Expected Services`);
  lines.push(``);
  if (profile.expectedServices.length === 0) {
    lines.push(`_No services detected._`);
  } else {
    lines.push(table(
      ["Service", "Kind", "Build Command", "Start / Output", "Health Path", "Route"],
      profile.expectedServices.map((s) => [
        s.name,
        s.kind,
        s.buildCommand ?? "—",
        s.startCommand ?? s.outputPath ?? "—",
        s.healthPath ?? "—",
        s.route ?? "—",
      ]),
    ));
  }
  lines.push(``);

  // ── Expected Routes ──────────────────────────────────────────────────────────

  lines.push(`## Expected Routes`);
  lines.push(``);
  if (profile.expectedRoutes.length === 0) {
    lines.push(`_No routes detected._`);
  } else {
    lines.push(table(
      ["Path", "Target", "Type"],
      profile.expectedRoutes.map((r) => [r.path, r.target, r.type]),
    ));
  }
  lines.push(``);

  // ── Expected Environment Variables ───────────────────────────────────────────

  lines.push(`## Expected Environment Variables`);
  lines.push(``);
  lines.push(`> Values are never included in this report — only key names and categories.`);
  lines.push(``);
  if (profile.expectedEnv.length === 0) {
    lines.push(`_No environment variables detected._`);
  } else {
    const categories = [...new Set(profile.expectedEnv.map((e) => e.category))].sort();
    for (const cat of categories) {
      const entries = profile.expectedEnv.filter((e) => e.category === cat);
      lines.push(`### ${cat.charAt(0).toUpperCase() + cat.slice(1)}`);
      lines.push(``);
      lines.push(table(
        ["Key Name", "Required", "Secret", "Description"],
        entries.map((e) => [
          `\`${e.name}\``,
          e.required ? "Yes" : "No",
          e.secret   ? "Yes" : "No",
          e.description || "—",
        ]),
      ));
      lines.push(``);
    }
  }

  // ── Safety Notes ─────────────────────────────────────────────────────────────

  if (profile.safetyNotes.length > 0) {
    lines.push(`## Safety Notes`);
    lines.push(``);
    for (const note of profile.safetyNotes) {
      lines.push(`- ⚠️ ${note}`);
    }
    lines.push(``);
  }

  // ── Recommended Next Steps ───────────────────────────────────────────────────

  if (profile.recommendedNextSteps.length > 0) {
    lines.push(`## Recommended Next Steps`);
    lines.push(``);
    profile.recommendedNextSteps.forEach((step, i) => {
      lines.push(`${i + 1}. ${step}`);
    });
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`_Generated by Prisom Project Panel — Sprint 71 Project Profile Framework_`);

  return lines.join("\n");
}
