import type {
  FinalReadinessAudit,
  FinalReadinessCheck,
  FinalReadinessCategory,
} from "./final-readiness-types";

const CATEGORY_LABELS: Record<FinalReadinessCategory, string> = {
  qa:            "QA Verification",
  release:       "Release Candidate & Signoff",
  migration:     "Migration Workflow",
  staging:       "Staging & Trial",
  ecommerce:     "Ecommerce",
  routing:       "Routing & DNS",
  monitoring:    "Monitoring",
  logs:          "Logs",
  backups:       "Backups",
  security:      "Security & Secrets",
  team:          "Team",
  documentation: "Documentation",
  training:      "Operator Training",
  launch_day:    "Launch Day",
  post_launch:   "Post-Launch",
};

const CATEGORY_ORDER: FinalReadinessCategory[] = [
  "qa", "release", "migration", "staging", "ecommerce",
  "routing", "monitoring", "logs", "backups", "security",
  "team", "documentation", "training", "launch_day", "post_launch",
];

const STATUS_ICON: Record<FinalReadinessCheck["status"], string> = {
  pass:           "✅",
  warning:        "⚠️",
  blocked:        "🚫",
  manual:         "🔲",
  not_applicable: "—",
};

export function exportFinalReadinessAudit(audit: FinalReadinessAudit): string {
  const lines: string[] = [
    "# FINAL_READINESS_AUDIT.md",
    "",
    `**Project:** ${audit.projectId}`,
    `**Generated:** ${new Date(audit.generatedAt).toUTCString()}`,
    `**Status:** ${audit.status.replace(/_/g, " ").toUpperCase()}`,
    `**Score:** ${audit.score}%`,
    "",
    "> Read-only — final audit only. No production mutation.",
    "",
    "---",
    "",
    "## Final Recommendation",
    "",
    `> **${audit.finalRecommendation}**`,
    "",
    "---",
    "",
  ];

  if (audit.blockers.length > 0) {
    lines.push("## ⛔ Blockers", "");
    for (const b of audit.blockers) lines.push(`- ${b}`);
    lines.push("");
  }

  if (audit.warnings.length > 0) {
    lines.push("## ⚠️ Warnings", "");
    for (const w of audit.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  if (audit.readyEvidence.length > 0) {
    lines.push("## ✅ Confirmed Evidence", "");
    for (const ev of audit.readyEvidence) lines.push(`- ${ev}`);
    lines.push("");
  }

  lines.push("---", "", "## Readiness Checks", "");

  for (const cat of CATEGORY_ORDER) {
    const catChecks = audit.checks.filter((c) => c.category === cat);
    if (catChecks.length === 0) continue;
    lines.push(`### ${CATEGORY_LABELS[cat]}`, "");
    for (const c of catChecks) {
      const icon = STATUS_ICON[c.status];
      lines.push(`#### ${icon} ${c.label}`);
      lines.push("");
      lines.push(c.description);
      if (c.required) lines.push("", "_Required._");
      if (c.evidence) lines.push("", `**Evidence:** ${c.evidence}`);
      if (c.nextStep) lines.push("", `**Next step:** ${c.nextStep}`);
      lines.push("");
    }
  }

  lines.push("---", "", "## Known Issues Register", "");
  if (audit.knownIssues.length === 0) {
    lines.push("No known issues recorded.", "");
  } else {
    for (const ki of audit.knownIssues) {
      const sevIcon = ki.severity === "critical" || ki.severity === "high" ? "🔴" : ki.severity === "medium" ? "🟡" : "🟢";
      lines.push(`### ${sevIcon} ${ki.title}`);
      lines.push(``, `**Severity:** ${ki.severity} | **Blocks launch:** ${ki.blocksLaunch ? "Yes" : "No"}`);
      lines.push(``, ki.description);
      lines.push("", "**Evidence to check:**");
      for (const ev of ki.evidenceToCheck) lines.push(`- ${ev}`);
      lines.push("", `**Recommended action:** ${ki.recommendedAction}`, "");
    }
  }

  if (audit.recommendedNextSteps.length > 0) {
    lines.push("---", "", "## Recommended Next Steps", "");
    for (const step of audit.recommendedNextSteps) lines.push(`- ${step}`);
    lines.push("");
  }

  lines.push(
    "---",
    "",
    "## Safety Notes",
    "",
    "- This report is read-only and generates no production changes.",
    "- All manual steps must be completed by a named operator before cutover.",
    "- Re-generate this report after fixing blockers to confirm readiness.",
    "- Do not proceed to production cutover while this report shows BLOCKED.",
    "",
    "---",
    "",
    "_Generated by Prisom Project Panel. Read-only — final audit only. No production mutation._",
    "",
  );

  return lines.join("\n");
}
