import type {
  StopBuildGateReport,
  StopBuildGateCheck,
  StopBuildDecision,
} from "./stop-build-types";

const CATEGORY_LABELS: Record<StopBuildGateCheck["category"], string> = {
  core_platform:     "Core Platform",
  migration_workflow: "Migration Workflow",
  launch_workflow:   "Launch Workflow",
  safety:            "Safety",
  documentation:     "Documentation",
  operations:        "Operations",
  client_handover:   "Client Handover",
};

const CATEGORY_ORDER: StopBuildGateCheck["category"][] = [
  "core_platform", "migration_workflow", "launch_workflow",
  "safety", "documentation", "operations", "client_handover",
];

const DECISION_LABELS: Record<StopBuildDecision, string> = {
  stop_building_ready_to_launch: "🟢 STOP BUILDING — READY TO LAUNCH",
  fix_blockers_only:             "🟡 FIX BLOCKERS ONLY — THEN LAUNCH",
  continue_building:             "🔵 CONTINUE BUILDING",
};

const STATUS_ICON: Record<StopBuildGateCheck["status"], string> = {
  pass:    "✅",
  warning: "⚠️",
  blocked: "🚫",
  manual:  "🔲",
};

export function exportStopBuildGateReport(report: StopBuildGateReport): string {
  const lines: string[] = [
    "# STOP_BUILD_GATE.md",
    "",
    `**Project:** ${report.projectId}`,
    `**Generated:** ${new Date(report.generatedAt).toUTCString()}`,
    `**Decision:** ${DECISION_LABELS[report.decision]}`,
    "",
    "> Read-only — stop-build gate documentation only. No production mutation.",
    "",
    "---",
    "",
    "## Final Operator Message",
    "",
    `> **${report.finalOperatorMessage}**`,
    "",
    "---",
    "",
  ];

  if (report.blockers.length > 0) {
    lines.push("## ⛔ Blockers", "");
    for (const b of report.blockers) lines.push(`- ${b}`);
    lines.push("");
  }

  if (report.warnings.length > 0) {
    lines.push("## ⚠️ Warnings", "");
    for (const w of report.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  lines.push("---", "", "## Gate Checks", "");

  for (const cat of CATEGORY_ORDER) {
    const catChecks = report.checks.filter((c) => c.category === cat);
    if (catChecks.length === 0) continue;
    lines.push(`### ${CATEGORY_LABELS[cat]}`, "");
    for (const c of catChecks) {
      const icon = STATUS_ICON[c.status];
      lines.push(`- ${icon} **${c.label}**`);
      lines.push(`  ${c.description}`);
    }
    lines.push("");
  }

  lines.push("---", "", "## Allowed Next Work", "");
  for (const item of report.allowedNextWork) lines.push(`- ✅ ${item}`);
  lines.push("");

  lines.push("---", "", "## Blocked Next Work", "");
  for (const item of report.blockedNextWork) lines.push(`- 🚫 ${item}`);
  lines.push("");

  lines.push(
    "---",
    "",
    "_Generated by Prisom Project Panel. Read-only — stop-build gate documentation only. No production mutation._",
    "",
  );

  return lines.join("\n");
}
