import type { LaunchDaySupportReport, LaunchDayTimelineItem } from "./launch-day-types";

const PHASE_LABELS: Record<LaunchDayTimelineItem["phase"], string> = {
  pre_launch:      "Pre-Launch",
  cutover:         "Cutover",
  smoke_test:      "Smoke Tests",
  ecommerce:       "Ecommerce Checks",
  monitoring:      "Monitoring",
  client_handover: "Client Handover",
  post_launch:     "Post-Launch",
};

const PHASE_ORDER: LaunchDayTimelineItem["phase"][] = [
  "pre_launch", "cutover", "smoke_test", "ecommerce",
  "monitoring", "client_handover", "post_launch",
];

const STATUS_ICON: Record<LaunchDayTimelineItem["status"], string> = {
  pass:    "✅",
  warning: "⚠️",
  blocked: "🚫",
  manual:  "🔲",
  pending: "⏳",
};

export function exportLaunchDaySupportReport(report: LaunchDaySupportReport): string {
  const lines: string[] = [
    "# LAUNCH_DAY_SUPPORT_REPORT.md",
    "",
    `**Project:** ${report.projectId}`,
    `**Generated:** ${new Date(report.generatedAt).toUTCString()}`,
    `**Status:** ${report.status.replace(/_/g, " ").toUpperCase()}`,
    "",
    "> Read-only — evidence collection and manual operator support only. No production mutation.",
    "",
    "---",
    "",
  ];

  // Blockers
  if (report.blockers.length > 0) {
    lines.push("## ⛔ Blockers", "");
    for (const b of report.blockers) lines.push(`- ${b}`);
    lines.push("");
  }

  // Warnings
  if (report.warnings.length > 0) {
    lines.push("## ⚠️ Warnings", "");
    for (const w of report.warnings) lines.push(`- ${w}`);
    lines.push("");
  }

  // Timeline grouped by phase
  lines.push("## Launch-Day Timeline", "");
  for (const phase of PHASE_ORDER) {
    const phaseItems = report.timeline.filter((t) => t.phase === phase);
    if (phaseItems.length === 0) continue;
    lines.push(`### ${PHASE_LABELS[phase]}`, "");
    for (const item of phaseItems) {
      const icon = STATUS_ICON[item.status] ?? "⏳";
      lines.push(`#### ${icon} ${item.label}`);
      lines.push("");
      lines.push(item.description);
      if (item.required) lines.push("", "_Required step._");
      if (item.command) {
        lines.push("", "**Command:**", "```bash", item.command, "```");
      }
      if (item.evidence) lines.push("", `**Evidence to collect:** ${item.evidence}`);
      if (item.operatorNote) lines.push("", `**Operator note:** ${item.operatorNote}`);
      if (item.safetyNote) lines.push("", `⚠️ **Safety note:** ${item.safetyNote}`);
      lines.push("");
    }
  }

  // Operator checklist
  lines.push("---", "", "## Operator Checklist", "");
  for (const item of report.operatorChecklist) lines.push(`- [ ] ${item}`);
  lines.push("");

  // Smoke commands
  lines.push("---", "", "## Smoke Check Commands", "", "```bash");
  for (const cmd of report.smokeCommands) lines.push(cmd);
  lines.push("```", "");

  // Required evidence
  lines.push("---", "", "## Required Evidence", "");
  for (const ev of report.requiredEvidence) lines.push(`- [ ] ${ev}`);
  lines.push("");

  // Rollback reminder
  lines.push("---", "", "## Rollback Reminder", "");
  for (const line of report.rollbackReminder) lines.push(line);
  lines.push("");

  // Recommended next steps
  if (report.recommendedNextSteps.length > 0) {
    lines.push("---", "", "## Recommended Next Steps", "");
    for (const step of report.recommendedNextSteps) lines.push(`- ${step}`);
    lines.push("");
  }

  // Manual notes section
  lines.push(
    "---",
    "",
    "## Manual Notes",
    "",
    "> Use this section to record operator notes, timestamps, and decisions made on launch day.",
    "",
    "| Time | Operator | Action / Decision |",
    "| --- | --- | --- |",
    "| | | |",
    "| | | |",
    "| | | |",
    "",
    "---",
    "",
    "_Generated by Prisom Project Panel. Read-only — no production mutation._",
    "",
  );

  return lines.join("\n");
}
